ClosedXML/ClosedXML

ClosedXML/ClosedXML/ClosedXML/Excel/XLWorkbook_Save.cs

PR originally logged at https://closedxml.codeplex.com/SourceControl/network/forks/igitur/ClosedXML/contribution/8516
When deleting a worksheet, the pivot cache parts have to be deleted as well, else Excel complains of a corrupt file.
There are 2 cases:
When a worksheet containing a pivot table is deleted, the pivot cache has to be deleted.
When a worksheet that is the source to a pivot table on another sheet is deleted, the pivot cache also has to be deleted.
I used a snippet found at http://blogs.msdn.com/b/vsod/archive/2010/02/05/how-to-delete-a-worksheet-from-excel-using-open-xml-sdk-2-0.aspx for the latter part.

Delete pivotcache when deleting a sheet

---

ClosedXML/ClosedXML.csproj
ClosedXML_Examples/ClosedXML_Examples.csproj
ClosedXML_Net3.5/ClosedXML_Net3.5.csproj
ClosedXML_Sandbox/ClosedXML_Sandbox.csproj
ClosedXML_Tests/ClosedXML_Tests.csproj
ClosedXML_Tests/Excel/CalcEngine/FunctionsTests.cs

Use NUnit3 attribute: OneTimeSetUp instead of TestFixtureSetUp.
Remove Code Analysis configurations, which are disabled anyway.

Remove warnings

---

ClosedXML/Excel/CalcEngine/Expression.cs
ClosedXML_Tests/Excel/CalcEngine/DateAndTimeTests.cs

The expression engine currently uses an Invariant culture to parse dates. This leads to unexpected results. Rather use the culture as explicitly set in the current thread. New tests included.
Originally logged at https://closedxml.codeplex.com/SourceControl/network/forks/igitur/ClosedXML/contribution/8276

Parse dates with current culture

---

ClosedXML/ClosedXML.csproj
ClosedXML/Excel/NamedRanges/IXLNamedRange.cs
ClosedXML_Net3.5/ClosedXML_Net3.5.csproj

Suppress warning CS1591 (Missing XML comment for publicly visible type or member) in order to reduce AppVeyor log output.

Suppress warning CS1591

---

ClosedXML/ClosedXML/ClosedXML/Excel/Cells/XLCell.cs
ClosedXML/ClosedXML/ClosedXML_Tests/Excel/Cells/XLCellTests.cs

I have some users who have set their short date format (in Regional settings) to dd/MM/yy (note the century digits are omitted). I don't like this date format either, but they insist on using it.
This creates the odd situation that sometimes when setting a date and then retrieving it, it is out by 1 century, e.g. 11 June 2035 gets returned as 11 June 1935. 
This pull request fixes it and adds a test to the test suite.
Originally logged at https://closedxml.codeplex.com/SourceControl/network/forks/igitur/ClosedXML/contribution/8275

Fix datetime bug with short date format

---

ClosedXML/Excel/AutoFilters/XLAutoFilter.cs
ClosedXML_Tests/Excel/AutoFilters/AutoFilterTests.cs

Clearing AutoFilter shouldn't throw an exception, even if no AutoFilter is enabled. It should just silently continue.

Clearing AutoFilter shouldn't throw an exception

---

ClosedXML/ClosedXML.csproj
ClosedXML/Excel/XLWorkbook_Load.cs
ClosedXML/Excel/XLWorkbook_Save.cs
ClosedXML/Utils/XmlEncoder.cs
ClosedXML_Net3.5/ClosedXML_Net3.5.csproj
ClosedXML_Tests/ClosedXML_Tests.csproj
ClosedXML_Tests/Excel/Cells/XLCellTests.cs
ClosedXML_Tests/Excel/Misc/XmlEncoderTests.cs

https://closedxml.codeplex.com/SourceControl/network/forks/NickNack2020/ClosedXml/contribution/8268
Possibly fixes #63
Added XML encoder util. Will encode invalid XML characters based on
XML Spec http://www.w3.org/TR/REC-xml/#charsets
-Encode shared string on save
-Decoded shared strings on load
Quick fix only applied to shared strings,
could be other problematic areas in code
Conflicts:
ClosedXML_Tests/ClosedXML_Tests.csproj
ClosedXML_Tests/Excel/Cells/XLCellTests.cs

NickNack2020's fix for invalid char

---

ClosedXML/Attributes/ColumnOrderAttribute.cs
ClosedXML/ClosedXML.csproj
ClosedXML/Excel/Cells/XLCell.cs
ClosedXML_Net3.5/ClosedXML_Net3.5.csproj
ClosedXML_Tests/Excel/Tables/TablesTests.cs

Add custom attribute to specify column order of object exported.
Implement DisplayName() attribute for .NET3.5 to replicate Display() attribute for .NET4+.

Add custom attribute to specify column order of object exported.

---

ClosedXML/Excel/Cells/XLCell.cs
ClosedXML/Excel/Columns/XLColumn.cs
ClosedXML/Excel/Ranges/IXLRangeBase.cs
ClosedXML/Excel/Ranges/XLRangeBase.cs
ClosedXML/Excel/Rows/XLRow.cs
ClosedXML/Excel/XLWorksheet.cs
ClosedXML_Tests/ClosedXML_Tests.csproj
ClosedXML_Tests/Excel/Ranges/UsedAndUnusedCellsTests.cs

Expose new Cells() function to iterate over cells, including unused cells inside range, but excluding unused cells outside range.
This is in reference to #82 , where iteration over cells skipped unused cells inside a reference range. The new overload with boolean parameter, optionally includes all those unused cells that fall within the range.

Expose new Cells() function to iterate over cells, including unused cells inside range, but excluding unused cells outside range.

---

ClosedXML/Extensions.cs

There is no need for checking if the item is already
in the HashSet. Thats what a HashSet is for.
.Add() returns false if the item is alread present.

Improve HasDuplicates<T>

---

ClosedXML/Excel/Cells/XLCell.cs
ClosedXML_Tests/Excel/Misc/FormulaTests.cs

Don't match parts of formula between single quotes (i.e. sheet names). Related to part of #90

Don't match parts of formula between single quotes (i.e. sheet names)

---

ClosedXML/Excel/XLWorkbook_Save.NestedTypes.cs
ClosedXML/Excel/XLWorkbook_Save.cs
ClosedXML_Tests/ClosedXML_Tests.csproj
ClosedXML_Tests/Excel/Saving/SavingTests.cs

For an existing workbook that is resaved, correctly retrieve the relId and readd it to the workbookPar.
Fixes https://closedxml.codeplex.com/workitem/9483

Multiple SaveAs calls causes InvalidCastException

---

ClosedXML/Excel/XLWorkbook_Load.cs

Extract method to parse cell value and reuse it for inline strings too. Previously inline strings with rich text failed.
Also clean up class formatting using CodeMaid.
Fixes #91.

Parse inline string with rich text correctly.

---

ClosedXML/Excel/ConditionalFormats/Save/XLCFContainsConverter.cs
ClosedXML/Excel/ConditionalFormats/Save/XLCFEndsWithConverter.cs
ClosedXML/Excel/ConditionalFormats/Save/XLCFNotContainsConverter.cs
ClosedXML/Excel/ConditionalFormats/Save/XLCFStartsWithConverter.cs
ClosedXML/Excel/XLWorkbook_Load.cs

Fixes #144 
Refines conditional formatting and loads certain attributes only for certain conditional formatting types. Based on documentation at https://msdn.microsoft.com/en-us/library/documentformat.openxml.spreadsheet.conditionalformattingrule%28v=office.15%29.aspx?f=255&MSPPError=-2147217396
Should improve loading of files generated in OpenOffice / LibreOffice.

Improve conditional formatting loading and saving

---

ClosedXML/Excel/XLWorkbook_Save.cs
ClosedXML_Tests/Excel/Saving/SavingTests.cs

Fixes #152 , #156
Even though the issue is fixed upstream in https://github.com/OfficeDev/Open-XML-SDK/pull/141 , we still need to enforce an invariant culture to support the .NET35 version of the library.

Force OpenXMLValidator to run under invariant culture

---

ClosedXML/Excel/PageSetup/XLHFItem.cs

Deduce default header and footer font from worksheet, rather than workbook default style.
Fixes #174

Deduce default header and footer font from worksheet

---

ClosedXML/Excel/XLWorkbook_Save.cs
ClosedXML_Tests/Excel/Saving/SavingTests.cs

Add VmlDrawing Id's to context to avoid reuse.

---

ClosedXML/Excel/XLWorkbook_Save.cs

It's possible to have duplicate default cell styles - occurs when file gets saved under different cultures.
We prefer the style that is named 'Normal'

Don't crash when file contains multiple default styles

---

ClosedXML/Excel/Ranges/XLRangeBase.cs

Performance improvement on creation of merged cells.
#300
```c#
using (var wb = new XLWorkbook(@"template.xlsx"))
{
var ws = wb.Worksheets.Worksheet(1);
var firstRow = ws.FirstRow();
var startTicks = DateTime.Now.Ticks;
using (var range = ws.Range(1, 1, 1, 20))
{
for (int i = 0; i <= 500; i++)
{
using (var rangeTo = ws.Range(2 + i, 1, 2 + i, 20))
{
range.CopyTo(rangeTo);
}
if (i % 10 == 0)
{
Console.WriteLine((DateTime.Now.Ticks - startTicks) / 10000);
}
}
}
wb.SaveAs(@"template_new.xlsx");
}
```
The performance is fairly improved, but is there a possibility that this change causes side effects?

Performance improvement on creation of merged cells

---

ClosedXML/Excel/Cells/XLCell.cs
ClosedXML/Excel/Ranges/XLRangeBase.cs
ClosedXML_Tests/Excel/Misc/CopyContentsTests.cs

Correctly set cell's address' worksheet when copying

---

ClosedXML/Excel/Ranges/XLRangeBase.cs
ClosedXML_Tests/Excel/Misc/StylesTests.cs

Use worksheet style if range base style is empty

---

ClosedXML/Attributes/XLColumnAttribute.cs
ClosedXML/Excel/CalcEngine/XLCalcEngine.cs
ClosedXML/Excel/Cells/XLCell.cs
ClosedXML/Excel/DataValidation/XLDataValidation.cs
ClosedXML/Excel/Drawings/XLPicture.cs
ClosedXML/Excel/Misc/XLFormula.cs
ClosedXML/Excel/Ranges/XLRangeBase.cs
ClosedXML/Excel/Tables/XLTable.cs
ClosedXML/Excel/XLWorkbook_Load.cs
ClosedXML/Excel/XLWorkbook_Save.cs
ClosedXML/Excel/XLWorksheet.cs
ClosedXML/Excel/XLWorksheets.cs
ClosedXML/Extensions.cs
ClosedXML/XLHelper.cs

`XLHelper.IsNullOrWhiteSpace` was a workaround for the .NET 3.5 build.

Remove obsolete XLHelper.IsNullOrWhiteSpace

---

ClosedXML/Excel/CalcEngine/CalcEngine.cs
ClosedXML/Excel/CalcEngine/Functions/MathTrig.cs
ClosedXML_Tests/ClosedXML_Tests.csproj
ClosedXML_Tests/Excel/CalcEngine/MathTrigTests.cs

Fixes #346 . 
Merge #406 first.

Correctly implement MOD function

---

ClosedXML/Excel/Ranges/XLRangeBase.cs
ClosedXML/Excel/XLWorksheet.cs
ClosedXML_Tests/Excel/NamedRanges/NamedRangesTests.cs

When copying a worksheet, named ranges on the source worksheet have to point to the new destination sheet

---

ClosedXML/Excel/NamedRanges/XLNamedRanges.cs
ClosedXML/Excel/XLWorkbook_Load.cs

Load named ranges in worksheet scope as is, without validation.

---

ClosedXML/Excel/Cells/XLCell.cs
ClosedXML/Excel/ConditionalFormats/XLConditionalFormats.cs
ClosedXML/Excel/Ranges/XLRangeBase.cs

Added Dispose call where it was missed. For large documents, this is critically important. Otherwise, callback lists grow by tens and hundreds of thousands, which leads to the freezing of the application.

Disposing of operating ranges.

---

ClosedXML/Excel/CalcEngine/Functions/MathTrig.cs
ClosedXML_Tests/Excel/CalcEngine/MathTrigTests.cs

The current behavior of the `INT` function was not the same as the one described on the office website https://support.office.com/en-us/article/INT-function-a6c4af9e-356d-4369-ab6a-cb1fd9d343ef
This PR corrects that. `INT` in Excel is equivalent to C#'s `Math.Floor`.
I added tests with the examples listed on the office website.

Correct INT function

---

ClosedXML/Extensions.cs

I mentioned this in this issue:
https://github.com/ClosedXML/ClosedXML/issues/545
Pretty simple fix but performance will suffer using decimal math here. All unit tests pass but as far as I can tell there is not actual test for this specific function.

Should not be using decimal math here as it is way slower than floating point

---

ClosedXML/Excel/CalcEngine/CalcEngineHelpers.cs
ClosedXML/Excel/CalcEngine/Functions/Statistical.cs
ClosedXML_Tests/Excel/CalcEngine/MathTrigTests.cs
ClosedXML_Tests/Excel/CalcEngine/StatisticalTests.cs

improve wildcard pattern matching for string conditions:
- support ? wildcard
- support escaping wildcards
- support the empty string as a condition
- cover special cases with unit tests
Splitting Pull Request #551, first part: string condition parsing.
The improvements themself are covered in the CalcEngineHelper.cs, tested by unit tests in the two test classes.
check with the behaviour of Excel ;)
I stumbled over two more problems I couldn't yet solve, but I don't think, these should be blocker for the PR:
1. Excel can deal with really big numbers. As I know from the past (not sure about the current state) it tended to be unprecise for really big or small numbers. With that in mind it could be that Excel does most calculations in floating point arithmetics, probably in `double` values, …

#548 enhance string condition capabilities of CalcEngine

---

ClosedXML/Excel/CalcEngine/Functions/MathTrig.cs
ClosedXML_Tests/Excel/CalcEngine/MathTrigTests.cs

improve functions from MathTrig category for CalcEngine,
where name starts with C to F and add unit tests
improved functions:
- COMBIN (tests were there already)
- FACT (+tests)
- FACTDOUBLE (+ tests)
new unit tests only:
- COS
- COSH
- DEGREES
- EVEN
- EXP
For FLOOR.MATH I refactored the tests so that each test checks one fact only: Splitted the long Test method with several assertions to a theory with several test cases where each executed test checks only one case.
Should work out straight forward through the code, I think.
compare with Execls behaviour.

Functions and tests math trig starting with C to F

---

ClosedXML/Excel/XLWorksheet.cs
ClosedXML_Tests/Excel/Loading/LoadingTests.cs
ClosedXML_Tests/Excel/Worksheets/XLWorksheetTests.cs

Fixes #574 
Allows a sheet to be copied that contains images with MoveAndSize placement.  It just temporarily sets the image placement to something that allows width/height to be set while copying excel sheets.
This was the easiest thing to do to fix the issue.  If you decide the width/height setters should not have that placement constraint then I'll be glad to change the PR to do that instead.
- Is there a blog post? no
- Does the knowledge base need an update? no
- Does this add new (C#) dependencies? no

Fix error when copying sheets with certain image anchors

---

ClosedXML/ClosedXML.csproj
ClosedXML/Excel/IXLWorkbook.cs
ClosedXML/Excel/XLWorkbook.cs

In order to make it easier to unit tests code that uses ClosedXML, I have created an IXLWorkbook interface to the XLWorkbook class. Now you can easily inject it with dependency injection with a wrapper to create the actual class when you need it, and it makes it possible to mock any calls to the workbook. Mentioned in this issue:
Fixes #550

Added interface file for XLWorkbook

---

ClosedXML/Excel/XLWorkbook_Load.cs

Fix "System.InvalidOperationException: Error in implicit conversion. Cannot convert null object." when pf.MultipleItemSelectionAllowed is null.

Fix System.InvalidOperationException: Error in implicit conversion. 

---

ClosedXML/Excel/XLWorkbook_Save.cs

If the source data for pivot is located on the second column, then an error will be thrown.

#596 Fix: Crash when opening file containing a pivot table created with Excel

---

ClosedXML/Excel/CalcEngine/Functions/MathTrig.cs
ClosedXML_Tests/Excel/CalcEngine/MathTrigTests.cs

SUMPRODUCT: Blank cells and cells with text should be treated as zeros

---

ClosedXML/Excel/Cells/XLCell.cs
ClosedXML_Tests/Excel/Cells/XLCellTests.cs

During #667 analysis I noticed that changing cell's R1C1 formula does not affect A1 formula if it's been set prior. This causes inconsistent state and wrong calculation as the A1 formula is used in the evaluation.
Code to reproduce the problem is in the unit test.

Clear FormulaA1 when FormulaR1C1 is set

---

ClosedXML/Excel/XLWorkbook_Load.cs
ClosedXML/Excel/XLWorkbook_Save.cs
ClosedXML_Tests/Excel/Loading/LoadingTests.cs

Fix issue #648  by adding support for the Protection.Objects property to the sheet load and save.
Changed LoadSheetProtection in XLWorkbook_Load to copy the state of the Objects property from the OpenXml object tot he ClosedXml object.
Changed GenerateWorksheetPartContent in XLWorkbook_Save.cs to copy the state of the Objects property from ClosedXml to the OpenXml object.
As per the reproduction code on #648 
- Is there a blog post?
- Does the knowledge base need an update?
- Does this add new (C#) dependencies?

Add persistence of Edit objects protection setting.

---

ClosedXML/ClosedXML.csproj
ClosedXML/Excel/Style/Colors/XLColor_Static.cs
ClosedXML/Excel/XLWorkbook_Load.cs
ClosedXML/Utils/ColorStringParser.cs

Workaround when parsing html color string fails

---

ClosedXML/Excel/Drawings/IXLPictures.cs
ClosedXML/Excel/Drawings/XLPictures.cs
ClosedXML/Excel/XLWorkbook_Save.cs
ClosedXML_Tests/Excel/ImageHandling/PictureTests.cs

This PR fixes #673, #655 
Previously, ClosedXML did not delete images from the file, only added them.
This PR
1. Puts deleted pictures into a separate collection and then removes them from a workbook as well.
2. Removes drawings that have no contents (it is not absolutely necessary, just prevents empty ```drawing``` sections from being stored in the file).
3. Original test expanded to check not only that pictures were deleted from a workbook in memory, but that they were removed from a file too.

FIX Pictures not being deleted

---

ClosedXML/Excel/Ranges/XLRange.cs
ClosedXML/Excel/Ranges/XLRangeBase.cs
ClosedXML_Tests/Excel/AutoFilters/AutoFilterTests.cs
ClosedXML_Tests/Excel/Ranges/InsertingRangesTests.cs

This PR fixes #604.
Here I implemented a test covering an exact scenario from the original issue, and also a bunch of test cases for ShiftColumns and ShiftRows methods, trying to cover as many variants of ranges relative positions as I could think of. 
To make them all passing I had to rewrite both methods in (I hope) more understandable form. Original versions of method caused ranges to become invalid when one of them laid inside of the other, and also could produce such weird ranges as "C1:B2"

FIX "Range is invalid" issue

---

ClosedXML/Excel/CalcEngine/Functions/Tally.cs

There were significant redundant uses of Linq where every .Count(), .Average(), .Sum() caused a repeated iteration and filtering of the expressions.  These changes adopt a lazy approach to acquiring the numerical values and avoid repeated .Count() calls etc.
It's one file.  Easy to review.  The key is line 14 `private IReadOnlyList<double> _numericValues;`
Any calls that use Tally.
Note: there are plenty of other places in the ClosedXML code where this type of inefficiency is in place, but this was the one I found and tackled.  Others may want to review any .Count() calls and property call .ToList() where it makes sense.
IMPORTANT: Calling `.Count() > 0` is not the same performance as calling `.Any()` (or `.Count != 0` when a list.).  Although possibly insignificant for small sets, it's …

Eliminated significant redundant iterations.

---

ClosedXML_Tests/Excel/Saving/SavingTests.cs

In my PR #641 I used a non-standard way of handling temporary files in unit tests. This PR fixes it.

Use existing class for handling temporary files in tests

---

ClosedXML/Excel/Cells/XLCell.cs

Profiling the application I discovered that XLAddress instances attached to each XLCell instance take a significant amount of memory. Not huge, of course, but still redundant.
If XLCell stores its own rowNumber, columnNumber, etc., it can create a new instance of XLAddress on demand, reducing overall memory consumption.
**Before:**
**After:**
Both screenshots were taken during PerformanceRunner.RunInsertTable operation, right before EmulateSave is called. As it may be observed, XLAddress instances consumed about 7 MB. 
This optimization does not seem to affect performance.

Create cell address on demand

---

ClosedXML/Excel/Cells/XLCell.cs
ClosedXML/Excel/ConditionalFormats/XLConditionalFormat.cs
ClosedXML_Tests/ClosedXML_Tests.csproj
ClosedXML_Tests/Excel/ConditionalFormats/ConditionalFormatCopyTests.cs

Copying cells between workbooks/Worksheets with conditional formats could never really work. Since the target range of the conditonal format was only set *after* the style, it would always reference a style in the source worksheet. In the best case, this would lead to ClosedXML being unable to save the new workbook. In the worse case, a kind of randomly selected style from the target worksheet would be used for the conditional format.
The PR is a simple change of order. Since the target range is set before, assigning the style for the conditional format correctly creates it in the target worksheet.
Copying a range with conditional formats between worksheets/workbooks.
- Is there a blog post?
Nope
- Does the knowledge base need an update?
Nope
- Does this add new (C#) dependencies?
Nope

range copy fix for conditional formats

---

ClosedXML/Excel/XLWorkbook_Save.cs

This PR fixes #714 
When the workbook is being saved each cell's type is determined only to decide if the certain cell is of type ```XLTableCellType.Total``` or not. If there are many thousands of cells this way is quite inefficient.
With this PR we prepare a complete set of those cells' addresses which are of the desired type - once per a worksheet, and then compare each cell address with this set. As a result, the saving operation performs significantly faster.

Improve determining if the cell is of type Table.Total

---

ClosedXML/Excel/CalcEngine/Expression.cs
ClosedXML/Excel/CalcEngine/Functions/Statistical.cs
ClosedXML_Tests/Excel/CalcEngine/StatisticalTests.cs

In the test ```CountBlank``` there was a mistake causing a range ```E3:E45``` to be not parsed properly as no worksheet was specified. By accident, the test worked fine, however.
This PR fixes and extends the original test, makes ```COUNTBLANK``` function more strict (it accepts only a single argument which must be either a cell range reference), and, in addition, prevents non-parsed strings from being split into chars during enumeration

Fix COUNTBLANK for invalid ranges

---

ClosedXML/Excel/Columns/XLColumn.cs
ClosedXML/Excel/Rows/XLRow.cs
ClosedXML_Tests/Excel/Columns/ColumnTests.cs
ClosedXML_Tests/Excel/Rows/RowTests.cs

Another funny mistake:
```
if (row <= 0)
RangeAddress.IsInvalid = false;
```

Treat negative row and column numbers as invalid

---

ClosedXML/Excel/CalcEngine/CalcEngineHelpers.cs
ClosedXML/Excel/CalcEngine/Functions/MathTrig.cs
ClosedXML/Excel/CalcEngine/Functions/Statistical.cs
ClosedXML/Excel/CalcEngine/Functions/Tally.cs
ClosedXML/Excel/CalcEngine/XLCalcEngine.cs
ClosedXML/Excel/Cells/XLCell.cs
ClosedXML/Excel/Ranges/IXLRangeBase.cs
ClosedXML/Excel/Ranges/XLRangeBase.cs
ClosedXML/Excel/XLWorksheet.cs
ClosedXML_Tests/Excel/CalcEngine/StatisticalTests.cs

Calculation of formulas referring to wide ranges (such as entire rows or columns) required enumeration of all cells included. For a single column, this might take a few seconds (and huge memory allocation); for the entire worksheet, the computation would never end due to the out-of-memory.
This PR optimizes a computation in the following ways:
1. ```IXLRangeBase``` now implements the ```GetCellValues``` method which returns cell values without a need to initialize ```XLCell``` instances. This alone would increase the performance noticeably and would not require modification of math and statistical functions, but still would fail on extremely wide ranges.
2. When obtaining cell values for some range this range is trimmed by current worksheet's used range. Say, if we know that last used row …

Optimize tally computations

---

ClosedXML/Utils/GraphicsUtils.cs

StringFormat.GenericTypographic return new object for each call.
StringFormat object has finalizer this create big load to finalization queue when call method AdjustToContents.

Cache StringFormat.GenericTypographic

---

ClosedXML/Excel/Ranges/IXLRanges.cs
ClosedXML/Excel/Ranges/XLRanges.cs
ClosedXML_Tests/Excel/Ranges/XLRangeBaseTests.cs

```IXLRanges``` has a method ```Clear()``` which I personally tried to use for removing all ranges from the collection, while it serves to a completely different purpose (to _clear_ data, formats, etc. for cells included in the ranges). To prevent such a confusion and to simplify collection clearing I propose adding ```RemoveAll()``` method to the interface. By default, it will dispose removed ranges, but this is optional.

Add RemoveAll method to IXLRanges

---

ClosedXML/Excel/XLWorkbook_ImageHandling.cs
ClosedXML/Excel/XLWorkbook_Save.cs

Take into account connection shapes when rebasing picture IDs. 
Fixes #769

Take into account connection shapes when rebasing picture IDs

---

ClosedXML/Excel/Coordinates/XLAddress.cs
ClosedXML/Excel/Ranges/XLRangeAddress.cs
ClosedXML/Excel/Ranges/XLRangeBase.cs
ClosedXML/Excel/XLWorksheet.cs
ClosedXML/XLHelper.cs

This is another small step in a refactoring of addresses and ranges handling.
With this PR I propose the following changes:
1. There was an optimization letting column letter of cell address to be initialized only once per instance of ```XLAddress```. After the initialization, it was being stored in the private field. The thing is, that the gain of this optimization would be less than 0.1 microseconds, so it would become noticeable only if the column letter of the **same** ```XLAddress``` instance is determined millions of times (which does not look as an ordinary scenario). And the drawback of such optimization was that **each** instance of ```XLAddress``` held a reference to a string value. And since the number of instances can easily reach a few million, the drawback overweights. So I …

Make cell addresses immutable

---

ClosedXML/ClosedXML.csproj
ClosedXML_Examples/ClosedXML_Examples.csproj
ClosedXML_Sandbox/ClosedXML_Sandbox.csproj
ClosedXML_Tests/ClosedXML_Tests.csproj

Change projects to use C# 7.2 by default.
I can't think of any possible side-effects, except that developers have to have a fairly recent version of Visual Studio or VS Code.

Change projects to use C# 7.2 by default.

---

ClosedXML/Excel/Cells/XLCell.cs
ClosedXML/XLHelper.cs
ClosedXML_Tests/Excel/Cells/XLCellTests.cs

This PR fixes #631.
Here I wrap `GetFormulaA1` into a try-catch block to prevent exceptions when formula became invalid due to shifting. We discussed that maybe we have to throw an exception at the moment such formula occurs but I assumed that since the formula could come from the saved file too and we actually support these improper formulas it is safer to return `#REF!` rather than throw an exception.
Supercedes #804

Catch the exceptions when the formula is not valid (i.e. shifted too far)

---

ClosedXML/Excel/NamedRanges/IXLNamedRange.cs
ClosedXML/Excel/NamedRanges/XLNamedRange.cs
ClosedXML/Excel/NamedRanges/XLNamedRanges.cs
ClosedXML_Tests/Excel/NamedRanges/NamedRangesTests.cs

Named Ranges can be at Worksheet or Workbook scope. Currently we use private properties and check for `Worksheet == null` to deduce the scope. This is a more explicit implementation.

Add and implement XLNamedRangeScope

---

ClosedXML/Excel/Cells/XLCell.cs
ClosedXML/Excel/ConditionalFormats/XLConditionalFormats.cs
ClosedXML/Excel/Patterns/Quadrant.cs
ClosedXML/Excel/Ranges/IXLRangeAddress.cs
ClosedXML/Excel/Ranges/IXLRanges.cs
ClosedXML/Excel/Ranges/Index/IXLRangeIndex.cs
ClosedXML/Excel/Ranges/Index/XLRangeIndex.cs
ClosedXML/Excel/Ranges/XLRangeAddress.cs
ClosedXML/Excel/Ranges/XLRangeBase.cs
ClosedXML/Excel/Ranges/XLRanges.cs
ClosedXML/Excel/XLWorksheet.cs
ClosedXML_Tests/Excel/Ranges/RangeIndexTest.cs
ClosedXML_Tests/Excel/Ranges/RangesConsolidationTests.cs

This is an alternative way to fix #796 (depends on #766, that's why so many changes in here). 
This fixes #792 accidentally too :). 
The solution @crypto-rsa has prepared is fine but, in my opinion, is too specific, since it addresses only issues with merged ranges. 
In this PR I define as interface `IXLRangeIndex` aimed to improve the performance of selecting intersecting ranges from the `XLRanges` collection. The implementation of this interface internally uses a [QuadTree](https://en.wikipedia.org/wiki/Quadtree) that splits entire worksheet to the squares from 16384×16384 at level 1 to 16×16 at level 10. To see how much performance is affected I prepared a few tests with 20000 merged ranges where I check if the target address hits in these ranges for 20000 times. With the default …

Implement indexing of XLRanges

---

ClosedXML/Excel/XLWorkbook.cs
ClosedXML_Tests/Excel/Saving/SavingTests.cs

Fixes saving as .xltx and .xltm files. #267 
The `SpreadsheetDocumentType` was not being set correctly for these file types, and Excel would not open them.

Template fix

---

ClosedXML/Excel/Cells/XLCellsCollection.cs
ClosedXML_Tests/Excel/Ranges/UsedAndUnusedCellsTests.cs

Fixes #339 
I can't believe it has not been unfixed for so long!
The original algorithm failed in cases like this:
```
| | |1|
| |1|1|
|1|1|1|
```

Fix determining the FirstColumnUsed

---

ClosedXML_Tests/Excel/Saving/SavingTests.cs

Just a test added. Doesn't fail, so no fix needed.

Test saving cell value with leading quotation mark and formula correctly

---

ClosedXML/Excel/Cells/XLCell.cs
ClosedXML/Excel/ConditionalFormats/IXLConditionalFormat.cs
ClosedXML/Excel/ConditionalFormats/XLConditionalFormat.cs
ClosedXML/Excel/Coordinates/IXLAddress.cs
ClosedXML/Excel/Coordinates/XLAddress.cs
ClosedXML/Excel/Drawings/IXLPicture.cs
ClosedXML/Excel/Drawings/XLPicture.cs
ClosedXML/Excel/NamedRanges/IXLNamedRange.cs
ClosedXML/Excel/NamedRanges/XLNamedRange.cs
ClosedXML/Excel/PageSetup/XLPageSetup.cs
ClosedXML/Excel/Ranges/IXLRangeAddress.cs
ClosedXML/Excel/Ranges/XLRangeAddress.cs
ClosedXML/Excel/Ranges/XLRangeBase.cs
ClosedXML/Excel/Rows/XLRow.cs
ClosedXML/Excel/Tables/IXLTable.cs
ClosedXML/Excel/Tables/XLTable.cs
ClosedXML/Excel/XLWorksheet.cs
ClosedXML_Tests/Excel/ConditionalFormats/ConditionalFormatCopyTests.cs
ClosedXML_Tests/Excel/ImageHandling/PictureTests.cs
ClosedXML_Tests/Excel/NamedRanges/NamedRangesTests.cs
ClosedXML_Tests/Excel/Saving/SavingTests.cs
ClosedXML_Tests/Excel/Tables/TablesTests.cs
ClosedXML_Tests/Excel/Worksheets/XLWorksheetTests.cs

This PR addresses #829.
Here I added unit tests covering different aspects of worksheets copying and implemented missing functionality.
To simplify the worksheet's method `CopyTo` I extracted part of the logic into corresponding classes (XLTable, XLPicture).

Fix issues with copying worksheets across workbooks

---

ClosedXML/Excel/XLWorkbook.cs
ClosedXML_Tests/Excel/Misc/XLWorkbookTests.cs

As revealed in #824, the cell cannot be accessed by its full address. E.g.
```
wb.Range("Sheet1!A1:B2");               // returns range
wb.Ranges("Sheet1!A1:B2,Sheet1!C1:E3"); // returns a collection of ranges
wb.Cell("Sheet1!C123");                 // returns null
```
In method `Cell()` we only searched for named ranges, not parsing the cell address.
This PR fixes this and adds a few unit tests for all these methods.

Get cell by full address

---

ClosedXML/Excel/XLWorkbook_Save.cs
ClosedXML_Tests/Excel/Clearing/ClearingTests.cs

When opening a file, clearing cells and saving the file, newly emptied cells were not correctly cleared in the XML.
@Pankraty This should address your problem that we discussed.

Correctly clear OpenXML cell value if ClosedXML cell value is empty

---

ClosedXML/Excel/Ranges/XLRangeBase.cs
ClosedXML_Tests/Excel/Ranges/InsertingRangesTests.cs
ClosedXML_Tests/Excel/Ranges/MergedRangesTests.cs

This PR fixes #855 by throwing the exception on an attempt to insert a negative or too big number of rows or columns. Existing tests for breaking merged ranges on shifting were split as they used a negative shift.

Disallow negative row or column count to be inserted

---

ClosedXML/Excel/Cells/XLCell.cs
ClosedXML/Excel/XLWorkbook_Save.cs
ClosedXML/Extensions.cs
ClosedXML_Tests/Excel/Cells/XLCellTests.cs

Improve XLCell.SetValue(object) by removing unnecessary TryParse functions

Improve XLCell.SetValue(object)

---

ClosedXML/Excel/Coordinates/XLAddress.cs
ClosedXML/Excel/NamedRanges/IXLNamedRange.cs
ClosedXML/Excel/NamedRanges/IXLNamedRanges.cs
ClosedXML/Excel/NamedRanges/XLNamedRange.cs
ClosedXML/Excel/NamedRanges/XLNamedRanges.cs
ClosedXML/Excel/Ranges/XLRangeAddress.cs
ClosedXML/Excel/XLWorkbook_Load.cs
ClosedXML/Excel/XLWorksheet.cs
ClosedXML_Tests/Excel/Coordinates/XLAddressTests.cs
ClosedXML_Tests/Excel/NamedRanges/NamedRangesTests.cs
ClosedXML_Tests/Excel/Ranges/XLRangeAddressTests.cs
ClosedXML_Tests/Excel/Worksheets/XLWorksheetTests.cs

This PR fixes #848.
When the worksheet is being deleted the references in named ranges are updated so that ranges from the deleted sheet were replaced with `#REF!`. For now, we do not support constructing invalid ranges from `#REF!` text so in `Ranges` getter we simply skip invalid ranges. 
To get collections of valid or invalid named ranges methods `ValidNamedRanges()` and `InvalidNamedRanges()` were added.

Invalidate named ranges when the worksheet is deleted

---

ClosedXML_Tests/Excel/Cells/XLCellTests.cs

`SetStringCellValues` test fails on my machine. It converts a typed value to a string and then applies string value to a cell expecting that cell format will be deduced from the value. But this works with string formatted in the current locale if I am not mistaken. So I replaced `.ToInvariantString()` to `.ToString()` and test became green.

Use current locale in the test instead of invariant culture

---

ClosedXML/ClosedXML.csproj

Upgrade System.Drawing.Common for netstandard2.0 to v4.5.0 (release).
Basing this against the `release-candidate` branch.

Upgrade System.Drawing.Common 

---

ClosedXML/Excel/Ranges/XLRangeBase.cs
ClosedXML_Tests/Excel/Ranges/UsedAndUnusedCellsTests.cs

This PR fixes #881.
The code for getting the first and the last used cells of the range had following problems:
1. It analyzed merged ranges only when `includeFormat` flag was true. I am convinced that merged ranges had to be considered even if `includeFormat` is false because it's not just the matter of formatting but it specifies how far the data extends.
2. When merged ranges were analyzed all other cells were ignored. Say, for the `FirstUsedCell` the first cell of merged ranges was returned even if there exist other cells with lower coordinates (see the original issue)
3. Besides, when merged ranges were analyzed the predicate passed into method was ignored. It did not affect `RangeUsed` method as it does not use predicate but produced an incorrect result if `FirstCellUsed` and …

Correctly determine used range when there are merged ranges on a worksheet (fix #881)

---

ClosedXML/Excel/AutoFilters/IXLAutoFilter.cs
ClosedXML/Excel/AutoFilters/IXLBaseAutoFilter.cs
ClosedXML/Excel/AutoFilters/XLAutoFilter.cs
ClosedXML_Tests/Excel/AutoFilters/AutoFilterTests.cs

Triggered by https://stackoverflow.com/questions/50537114/excel-closedxml-best-way-to-get-visible-rows-following-applying-setautofilte
This PR adds a helper property `VisibleRows` on autofilters.

Add helper property VisibleRows for autofilters

---

ClosedXML/Excel/Cells/IXLCell.cs
ClosedXML/Excel/Cells/XLCell.cs
ClosedXML/Extensions.cs

Before continuing work on #908 , let's first clean up and consolidate `XLCell.InsertData` and `XLCell.InsertTable`, which share a lot of logic.

Consolidate XLCell.InsertData and XLCell.InsertTable

---

ClosedXML/Excel/Cells/XLCell.cs
ClosedXML/Excel/XLWorkbook_Save.cs
ClosedXML_Tests/Excel/Cells/XLCellTests.cs

For generating `Item` elements in pivot table cache, the value of a cell is requested. For cells with formulas, this sometimes failed (e.g. an unsupported function). This should not prohibit the saving process from completing.
Depends on #904

Don't choke on pivot table saving when formulas fail

---

ClosedXML/Excel/XLWorkbook_Save.cs
ClosedXML_Tests/Excel/PivotTables/XLPivotTableTests.cs

Current pivot table page fields are saved according to the order of the underlying fields in the data source. 
This PR changes this to maintain pivot table page field order.
Depends on #905

Maintain pivot table page field order

---

ClosedXML/Excel/Tables/IXLTableRange.cs
ClosedXML/Excel/Tables/IXLTableRows.cs
ClosedXML/Excel/Tables/XLTableRow.cs
ClosedXML/Excel/Tables/XLTableRows.cs
ClosedXML_Tests/Excel/Tables/TablesTests.cs

Table row deletion not working correctly because row is deleted (range is shrunk) and then table is shrunk again.

Delete table rows correctly

---

ClosedXML/Excel/XLWorksheet.cs
ClosedXML_Tests/Excel/Ranges/XLRangeAddressTests.cs

Full span ranges (e.g. full rows, full columns and entire worksheets) should not be affected by range deletions and insertions.
Basing this on `develop`

Exclude full span addresses from range change notifications

---

ClosedXML/Excel/Tables/IXLTable.cs
ClosedXML/Excel/Tables/XLTable.cs
ClosedXML/Excel/Tables/XLTableRow.cs
ClosedXML_Tests/Excel/Tables/AddingAndReplacingTableDataTests.cs
ClosedXML_Tests/Excel/Tables/TablesTests.cs

Fixes #901 
Depends on ~#910~ 
This PR adds the ability to replace existing data in a table with new records or appending data to the table. If the new table has more records than previously, the table is grown and rows beneath the table are shifted down. Similarly, when the number of new records is less than the old tables', the table is shrunk and the rows below the table are shifted up.
This PR copies code from `XLCell.InsertData` and `XLCell.InsertTable` (modified). This PR doesn't check that the structure of the data (or even the number of fields per record) is consistent with that number and types of fields currently in the table. I leave that up to the user, who might deliberately want to mix data types in a table.

Append and replace table data

---

ClosedXML/Excel/Exceptions/ClosedXMLException.cs
ClosedXML/Excel/Exceptions/EmptyTableException.cs
ClosedXML/Excel/XLWorkbook_Save.cs
ClosedXML_Tests/Excel/Tables/TablesTests.cs

Depends on ~#908~
Throws exception when trying to save a file with a table with no datarange.

Disallow table with null .DataRange when saving

---

ClosedXML/Excel/Ranges/IXLRange.cs
ClosedXML/Excel/Ranges/XLRange.cs
ClosedXML/Excel/Tables/IXLTable.cs
ClosedXML/Excel/Tables/IXLTableField.cs
ClosedXML/Excel/Tables/IXLTableRange.cs
ClosedXML/Excel/Tables/XLTable.cs
ClosedXML/Excel/Tables/XLTableField.cs
ClosedXML/Excel/Tables/XLTableRange.cs
ClosedXML_Tests/Excel/Tables/AddingAndReplacingTableDataTests.cs
ClosedXML_Tests/Excel/Tables/TablesTests.cs

Depends on ~#908~
Some tables have "extra columns" with formulas and values. When replacing/appending data, one would sometimes want to propagate these extra columns down to the latest row. Very similar to what Excel will do in a table.

Propagate extra table columns when changing data

---

ClosedXML/Excel/XLWorkbook_Load.cs
ClosedXML/Excel/XLWorkbook_Save.cs
ClosedXML/Utils/OpenXmlHelper.cs
ClosedXML_Tests/Excel/Styles/ColorTests.cs

Currently, we have 6 nearly identical `switch`-es to convert ClosedXML colors to OpenXML format. For sparklines, we'd have to add 8 more as each color to be saved must be converted to its own class (`FirstMarkerColor`, `LastMarkerColor`, etc.). That's obviously insane.
This PR replaces all those `switch`-es with a single method that may be utilized by sparklines too.

Aggregate color conversion in one place

---

ClosedXML/Excel/Drawings/XLPictures.cs
ClosedXML/Excel/IXLWorkbook.cs
ClosedXML/Excel/Tables/IXLTables.cs
ClosedXML/Excel/Tables/XLTables.cs
ClosedXML/Excel/XLWorkbook.cs
ClosedXML_Tests/Excel/ImageHandling/PictureTests.cs
ClosedXML_Tests/Excel/Tables/TablesTests.cs

Some helper methods added.
I'm not convinced about replacing `ArgumentException` with `ClosedXMLEntityNotFoundException`. I can see the use of having our own exception, but it also feels inconsistent with other places where `ArgumentException` is thrown.

Add table helper methods

---

ClosedXML/XLHelper.cs
ClosedXML_Tests/Excel/Tables/TablesTests.cs

http://www.criticaltosuccess.com/allowed-characters-in-range-names/
> Range names must start with a letter, underscore, or backslash. Following characters must be letters or numbers, periods, or underscores. You cannot use spaces or any character combination that looks like a cell reference.
Fixes #997

Allow names to start with backslash

---

ClosedXML/Excel/XLWorksheet.cs
ClosedXML_Tests/Excel/Ranges/InsertingRangesTests.cs

Sort ranges to shift before enumerating through them to avoid new target address conflicting with existing range

---

ClosedXML/Excel/Ranges/XLRangeConsolidationEngine.cs
ClosedXML_Tests/Examples/MiscTests.cs
ClosedXML_Tests/Excel/Ranges/RangesConsolidationTests.cs

This PR aims to fix #968 but also discloses the bug in the `CellsUsed()` method.
Fixes #973 
Fixes #968

Fix ranges consolidation

---

ClosedXML/Excel/ConditionalFormats/XLConditionalFormat.cs
ClosedXML/Excel/ConditionalFormats/XLConditionalFormats.cs
ClosedXML/Excel/Ranges/Index/XLRangeIndex.cs
ClosedXML/Excel/Ranges/XLRanges.cs

This PR partially fixes #993. I used a worksheet 2510 from the original file. Before this PR saving took 69.5 sec, now it takes only 12.7 sec. Still far from perfect but definitely much better.
To achieve this I modified a ranges indexing algorithm so it wouldn't apply to small collections (less than 20 items). The number 20 was chosen empirically: our QuadTree implementation is 10 levels deep and each level may require one or a few checks for intersections. Changing the constant value in a range (10 .. 70) barely affected the performance (the difference was <1%).
[993_sample2.xlsx](https://github.com/ClosedXML/ClosedXML/files/2476134/993_sample2.xlsx)

Optimize the performance of searching range intersections on small collections

---

ClosedXML/Excel/CalcEngine/Expression.cs

- When implicitly casting bool to string, use upper case (in line with Excel)
- Small improvement in type casting
- Use inline parameter declaration
- Add case for casting timespan to datetime

Improve implicit string casting

---

ClosedXML/Excel/NamedRanges/XLNamedRange.cs
ClosedXML/Excel/XLWorkbook_Save.cs
ClosedXML_Tests/Excel/NamedRanges/NamedRangesTests.cs

Fixes #1007 
Ranges referring to the deleted worksheets must be saved as `#REF!`, not `#REF!$A$1:$B$2`, otherwise, Excel complains that the file is corrupted.
Besides, I found that `RangeList` is not initialized properly. It does not seem to affect any other functionality as `Ranges` property was still correct, and `ToString()` method aggregated `RangeList` items to a single string anyway. But after I changed the saving logic it became essential.

Change the way invalid ranges are saved

---

ClosedXML/Excel/CalcEngine/Expression.cs
ClosedXML_Tests/Excel/CalcEngine/LogicalTests.cs
ClosedXML_Tests/Excel/CalcEngine/LookupTests.cs

I couldn't find any cases where they should be case sensitive. All tests pass currently. Not ruling out the fact that there might be exceptions.
Fixes #861

String comparisons should be case-insensitive. 

---

ClosedXML_Tests/Excel/Cells/XLCellTests.cs

The test TryGetValue_decimal_Good2 fails on my machine. My settings are:
This PR make the test culture-independent.

Make TryGetValue_decimal_Good2test environment-independent

---

ClosedXML/ClosedXML.csproj

To avoid unnecessary binding redirects, we can reference FastMember (unsigned) when building unsigned ClosedXML.

Reference FastMember (unsigned) when building unsigned ClosedXML

---

ClosedXML/Excel/CalcEngine/CalcEngine.cs
ClosedXML_Tests/Excel/Misc/FormulaTests.cs

Refactor digit and letter parsing to allow Unicode characters

---

ClosedXML/Excel/Cells/XLCell.cs
ClosedXML_Tests/Excel/CalcEngine/FormulaCachingTests.cs

Fixes #1124 
Results of operations on Dates can return either a double or a date (or possibly timespan). Cached values should be updated to reflect the type when `IXLCell.DataType` changes.

Change cached value type when data type changes 

---

ClosedXML/Excel/XLWorkbook_Load.cs
ClosedXML_Tests/Excel/Loading/LoadingTests.cs

<c> elements with missing r attribute: XLAddress constructor had parameters swapped

---

ClosedXML/Excel/XLWorksheet.cs
ClosedXML_Tests/Excel/Styles/StyleTests.cs

As @b0bi79 has discovered, ClosedXML does not assign the worksheet style to empty cells that belong to columns or rows which had been initialized before the worksheet style was set.
```
[TestCase("A1", TestName = "First cell")] // OK
[TestCase("A2", TestName = "Cell from initialized row")]  // Fails
[TestCase("B1", TestName = "Cell from initialized column")]  // Fails
[TestCase("D4", TestName = "Initialized cell")]  // OK
[TestCase("F6", TestName = "Non-initialized cell")]  // OK
public void CellTakesWorksheetStyle(string cellAddress)
{
using (var wb = new XLWorkbook())
{
var ws = wb.AddWorksheet("Sheet1");
ws.Column(2);
ws.Row(2);
ws.Cell("D4").Value = "Non empty";
ws.Style.Font.SetFontName("Arial");
ws.Style.Font.SetFontSize(9);
var cell = ws.Cell(cellAddress);
Assert.AreEqual("Arial", …
```

Correctly propagate worksheet style to cells from a worksheet

---

ClosedXML/Excel/CalcEngine/Expression.cs
ClosedXML_Tests/Excel/CalcEngine/CalcEngineExceptionTests.cs

Correctly throw DivisionByZeroException when denominator is zero.

---

ClosedXML/Utils/XmlEncoder.cs
ClosedXML_Tests/Excel/Misc/XmlEncoderTests.cs

Remove own implementation of `IsXmlChar`
Case-insensitive decoding of hex strings
Ignore _X (capital X) as XML escaping char for decoding. Fixes #1154

Ignore _X (capital X) as XML escaping char

---

ClosedXML/Excel/Comments/XLComment.cs
ClosedXML/Excel/Ranges/XLRangeBase.cs
ClosedXML_Tests/Excel/Comments/CommentsTests.cs
ClosedXML_Tests/Excel/Rows/RowTests.cs

In the `XLComment` constructor, the previous row's height is being looked up. If the row doesn't exist, we should avoid its creation in `RowsCollection`.
Also refactored `XLRangeBase.Delete` to make it more readable.
Fixes #1160

 Avoid creation of new item in Internals.RowsCollection when adding comment

---

ClosedXML/Excel/Cells/XLCell.cs
ClosedXML/Excel/Ranges/IXLRangeAddress.cs
ClosedXML/Excel/Ranges/IXLRangeBase.cs
ClosedXML/Excel/Ranges/XLRangeAddress.cs
ClosedXML/Excel/Ranges/XLRangeBase.cs
ClosedXML_Examples/BasicTable.cs
ClosedXML_Examples/Misc/ShowCase.cs
ClosedXML_Tests/Excel/Ranges/XLRangeAddressTests.cs
ClosedXML_Tests/Excel/Ranges/XLRangeBaseTests.cs

Previously, as commented in https://github.com/ClosedXML/ClosedXML/pull/1159/files#diff-03a6bc67d4fe134e5578c84c9fc4e29fL52 :
```c#
ws.Range("B2:F10").Range("B2").Address.ToString()
```
would return `C3` because the `B2` was treated as relative to the first range.
This PR breaks this and ensures that range strings are always treated as absolute, i.e. relative to the entire worksheet.
Range strings like `"1-3, 4, 7"` are still treated as relative.
The first few commits of this PR does some reorganising of methods: `Intersection()` is consolidated and `Relative` is moved to `IXLRangeBase` and made public.

Always treat "A1:B2" range strings as absolute

---

ClosedXML/Excel/Cells/XLCell.cs
ClosedXML/Excel/Ranges/XLRangeBase.cs
ClosedXML/Excel/XLCellsUsedOptions.cs
ClosedXML/Excel/XLClearOptions.cs
ClosedXML_Tests/Excel/Clearing/ClearingTests.cs
ClosedXML_Tests/Excel/Ranges/UsedAndUnusedCellsTests.cs

This PR unifies `XLClearOptions` with `XLCellUsedOptions` by adding a `MergedRanges` flag. For now, we use the `NormalFormats` flag to specify that merged ranges have to be cleared which looks counter-intuitive.
I'd suggest to include this in 0.94 too so that changes related to these flags came all at once.

Add flag MergedRanges to XLClearOptions to unify with XLCellUsedOptions

---

ClosedXML/Excel/EnumConverter.cs
ClosedXML/Excel/PivotTables/IXLPivotField.cs
ClosedXML/Excel/PivotTables/IXLPivotFields.cs
ClosedXML/Excel/PivotTables/IXLPivotTable.cs
ClosedXML/Excel/PivotTables/PivotStyleFormats/AbstractPivotFieldReference.cs
ClosedXML/Excel/PivotTables/PivotStyleFormats/IXLPivotFieldStyleFormats.cs
ClosedXML/Excel/PivotTables/PivotStyleFormats/IXLPivotStyleFormat.cs
ClosedXML/Excel/PivotTables/PivotStyleFormats/IXLPivotStyleFormats.cs
ClosedXML/Excel/PivotTables/PivotStyleFormats/IXLPivotTableStyleFormats.cs
ClosedXML/Excel/PivotTables/PivotStyleFormats/IXLPivotValueStyleFormat.cs
ClosedXML/Excel/PivotTables/PivotStyleFormats/PivotLabelFieldReference.cs
ClosedXML/Excel/PivotTables/PivotStyleFormats/PivotValueFieldReference.cs
ClosedXML/Excel/PivotTables/PivotStyleFormats/XLPivotFieldStyleFormats.cs
ClosedXML/Excel/PivotTables/PivotStyleFormats/XLPivotStyleFormat.cs
ClosedXML/Excel/PivotTables/PivotStyleFormats/XLPivotStyleFormatEnums.cs
ClosedXML/Excel/PivotTables/PivotStyleFormats/XLPivotStyleFormats.cs
ClosedXML/Excel/PivotTables/PivotStyleFormats/XLPivotTableStyleFormats.cs
ClosedXML/Excel/PivotTables/PivotStyleFormats/XLPivotValueStyleFormat.cs
ClosedXML/Excel/PivotTables/PivotValues/IXLPivotValues.cs
ClosedXML/Excel/PivotTables/PivotValues/XLPivotValues.cs
ClosedXML/Excel/PivotTables/XLPivotAreaValues.cs
ClosedXML/Excel/PivotTables/XLPivotField.cs
ClosedXML/Excel/PivotTables/XLPivotFields.cs
ClosedXML/Excel/PivotTables/XLPivotTable.cs
ClosedXML/Excel/XLWorkbook_Load.cs
ClosedXML/Excel/XLWorkbook_Save.cs
ClosedXML_Tests/Excel/PivotTables/XLPivotTableTests.cs

@b0bi79 @Pankraty 
Here is my alternative implementation. It removes the need for lambda functions and "builders". I think this is a cleaner API, althought the internals are a bit more messy than your implementation. Some of the new enum's could be better named. We can finalise that later.
I made some changes to e.g. `XLPivotValues` that should probably be submitted in a separate PR.
What do you think of this? Look at the unit test to see how to use it.
Closes #895

Alternative implementation of pivot table formats

---

ClosedXML/Excel/XLWorkbook.cs
ClosedXML/Excel/XLWorkbook_Load.cs
ClosedXML_Tests/TestHelper.cs

If a workbook is loaded with `XLWorkbook.OpenFromTemplate()`, it should be treated as brand new, i.e. no RelId's should be prepopulated.

Clear all RelId's if workbook is loaded from template.

---

ClosedXML/Excel/Style/XLFontKey.cs
ClosedXML/Excel/Style/XLNumberFormatKey.cs
ClosedXML_Tests/Excel/Styles/FontTests.cs
ClosedXML_Tests/Excel/Styles/NumberFormatTests.cs

This PR fixes the bug in `XLNumberFormatKey` equality check: the comparison was case-insensitive while it should be case-sensitive as, for example, `mm` stands for minutes while `MM` - for months.
Besides, it improves `XLFontKey.GetHashCode` in order to reduce memory allocations.
Closes #1073

Fixes in GetHashCode functions (1073)

---

ClosedXML/Excel/CalcEngine/CellRangeReference.cs
ClosedXML/Excel/Ranges/XLRangeBase.cs

As @b0bi79 has discovered, `XLRangeBase.Merge()` is not quite efficient: `cellsUsed` is enumerated multiple times.
In addition, `LastCellUsed()` method is called in `CellRangeReference` twice so this part was also improved.
In my testing example, the execution time changes from 17 sec to 11 sec (>130K random merges).

Improve Merge operation performance

---

ClosedXML/Excel/Patterns/Quadrant.cs
ClosedXML/Excel/Ranges/Index/IXLRangeIndex.cs
ClosedXML/Excel/Ranges/Index/XLRangeIndex.cs
ClosedXML/Excel/Ranges/XLRanges.cs
ClosedXML/Excel/XLWorksheet.cs
ClosedXML_Tests/Excel/Ranges/RangeIndexTest.cs

Description:
1. The method XLWorksheet.RegisterRangeIndex was never called so modified ranges did not change their positions in indices
2. Removing ranges from the index by passing IXLRangeBase instance is not possible as the instance may already change its address
(so it cannot be found in QuadTree). That is why the Remove method changed to accept IXLRangeAddress
3. Check range index type before adding a relocated range there to avoid typecast exception later on enumeration
See https://github.com/ClosedXML/ClosedXML/pull/1033#issuecomment-455412853
@sflanker you were absolutely right. I really made a serious bug. It took me 5 months to realize :(

Fix issues with ranges indexing

---

ClosedXML/Excel/Ranges/XLRangeBase.cs
ClosedXML_Tests/Excel/Ranges/RangeShiftingTests.cs

This PR addresses the performance issues of #1162.
I've created a small benchmark that fills the worksheet with some random data (2000 * 2000) and then removes the first row or column.
Before this PR it took 9.6-12.1 sec to fill the table and 5.8-7.0 sec to remove a row or a column (6 test runs).
With these chanegs it takes 9.1-12.3 sec to fill and 4.1-5.0 to remove (6 test runs).
I hoped the effect would be more significant.

Avoid creating new XLCell instances during range shifting

---

ClosedXML/Excel/Ranges/XLRangeBase.cs

Fixes #1220
I prepared a test example with around 100K merged ranges. Before this PR it took around 15 seconds to open it, with this PR - only 8. It took way longer to generate the file.
[1220_test.xlsx](https://github.com/ClosedXML/ClosedXML/files/3233115/1220_test.xlsx)
BTW, this file is challenging even for Excel: it hangs noticeably when trying to navigate to the last used cell.

Improve performance of loading workbooks having many merged ranges (#1220)

---

ClosedXML/ClosedXML.csproj

This PR replaces deprecated tag `licenseUrl` to `license`. 
See NuGet/Home#4628 for the reasoning.

Replace licenseUrl (deprecated) with license tag

---

ClosedXML/Excel/CalcEngine/Functions/Text.cs
ClosedXML/Excel/Ranges/IXLRangeAddress.cs
ClosedXML/Excel/Ranges/XLRangeAddress.cs
ClosedXML_Tests/Excel/CalcEngine/TextTests.cs
ClosedXML_Tests/Excel/Ranges/XLRangeAddressTests.cs

CONCATENATE may accept cell range references as parameters, but its implementation is tricky and we can't support the full scope that Excel supports. See added code comments for clarification. This improves it though.
Fixes #1264

Fix CONCATENATE for cell references

---

ClosedXML/Excel/XLWorksheetInternals.cs

Fixes #1276 
Interestingly, GC could not correctly collect all instances after WorksheetsInternal disposal. Maybe because of too many cycle references, it could not traverse all roots in a reasonable time.
With this fix, it works as intended (19 iterations of opening the workbook, Release mode):

Clear CellsCollection on WorksheetInternals disposal (#1276)

---

ClosedXML/Excel/Cells/XLCell.cs
ClosedXML/XLHelper.cs
ClosedXML_Tests/Excel/Misc/XlHelperTests.cs
ClosedXML_Tests/Excel/Tables/TablesTests.cs

Fix for issue ClosedXML#1192
ClosedXML/Excel/Cells/XLCell.cs Line 679
By following the example in the Issue
- Is there a blog post? No 
- Does the knowledge base need an update? Maybe?
- Does this add new (C#) dependencies? No 
Closes #1192

Fix for issue 1192

---

ClosedXML/Excel/CalcEngine/CalcEngine.cs
ClosedXML/Excel/CalcEngine/Token.cs
ClosedXML_Tests/Excel/CalcEngine/FunctionsTests.cs

Fixes #1324 
Previously, we parsed % sign only as a part of a numeric literal, but in fact, % in formulas is equivalent to /100 and such expressions as `(100+300)%` or `123%%` are perfectly valid.
I've also noticed that we do not parse expressions with multiple unary operators (e.g. `=---12`) correctly. This is also fixed.

Implement % operator and correctly parse expressions with multiple unary operators (--, ++)

---

ClosedXML/Excel/Cells/XLCell.cs
ClosedXML/Excel/Columns/XLColumn.cs
ClosedXML/Excel/Ranges/XLRangeBase.cs
ClosedXML/Excel/Ranges/XLRangeColumn.cs
ClosedXML/Excel/Ranges/XLRangeRow.cs
ClosedXML/Excel/Rows/XLRow.cs
ClosedXML/Excel/Tables/XLTable.cs
ClosedXML/Excel/XLWorksheet.cs

First commit changes some inheritance behaviour. Some methods were marked as `new`. This is change to `override` and the base class methods are now `virtual`.
Then, where possible, use `TryGetValue` to retrieve worksheets and named ranges and remove manual case insensitive lookup.

Replace String.Compare with TryGetValue

---

ClosedXML/Excel/XLWorksheet.cs
ClosedXML_Tests/Excel/Worksheets/XLWorksheetTests.cs

Deleted worksheets should not be allowed to be copied.

Prevent copying of deleted worksheets.

---

ClosedXML/Excel/CalcEngine/Expression.cs
ClosedXML_Tests/Excel/CalcEngine/FunctionsTests.cs

Fixed the Expression double conversion operator to handle string values

---

ClosedXML/ClosedXML.csproj
ClosedXML/Excel/Cells/XLCell.cs
ClosedXML/Extensions/ObjectExtensions.cs
ClosedXML/XLHelper.cs
ClosedXML_Tests/ClosedXML_Tests.csproj
ClosedXML_Tests/Excel/CalcEngine/FormulaCachingTests.cs
appveyor.yml

Fixes #1318
Fixes #1273
Fixes #1274 
One test is still failing due to andersnm/ExcelNumberFormat#23.
@igitur should we switch to `netcoreapp3.0` in tests or add it as a new target (the 4th one)?

Fix issues occurred when running tests on .Net Core 3.0

---

ClosedXML/Excel/CalcEngine/Functions/MathTrig.cs
ClosedXML_Tests/Excel/CalcEngine/MathTrigTests.cs

- Change the signature of CEILING and FLOOR to accept only 2 arguments, matching Excel behavior
- Invalid arguments to the CEILING and FLOOR (positive number and negative significance) throw NumberException, matching Excel behavior
- Fixed the mode argument behavior in FLOOR.MATH to match Excel behavior
- Implemented CEILING.MATH
Fixes #1366

CEILING and FLOOR fixes

---

ClosedXML/Excel/CalcEngine/CalcEngine.cs
ClosedXML/Excel/CalcEngine/CellRangeReference.cs
ClosedXML/Excel/CalcEngine/Expression.cs
ClosedXML/Excel/CalcEngine/Functions/MathTrig.cs
ClosedXML/Excel/CalcEngine/Functions/Tally.cs
ClosedXML/Excel/CalcEngine/XLCalcEngine.cs
ClosedXML_Tests/Excel/CalcEngine/FunctionsTests.cs

This PR is an alternative to #1311 (which uses regular expressions). This implementation walks the expression tree to determine whether `SUBTOTAL` is used in a formula of a cell.
Closes #1311 
@Pankraty Which approach do you prefer?

Exclude dependent SUBTOTAL formulas in SUBTOTAL evaluation

---

ClosedXML/Excel/XLWorkbook_Save.cs
ClosedXML_Tests/Excel/Worksheets/XLWorksheetTests.cs

Fixes #1383 
The issue occurred when there was no tab explicitly marked as active but there was a selected tab different than the first visible tab. On saving, we chose the first visible tab to become active while the selected tab remained selected. Excel showed it correspondingly.

When saving, mark the first selected tab as active if no active tabs exist (#1383)

---

ClosedXML/Excel/Cells/XLCell.cs
ClosedXML_Tests/Excel/Cells/XLCellTests.cs

Fixed an issue where an IEnumerable<DateTime?> with a null value would throw an error due to no null checking. It will now instead insert an empty Cell value.

Fix null DateTime in XLCell.InsertDataInternal with IEnumerable

---

ClosedXML_Tests/Excel/CalcEngine/MathTrigTests.cs

After I switched to ru-RU locale some of the fresh math-trig tests started to fail due to formatting numbers with comma as a decimal separator.

Make CEILING and FLOOR tests culture-independent

---

ClosedXML/ClosedXML.csproj
ClosedXML/Excel/Cells/XLCell.cs
ClosedXML/Excel/XLTheme.cs
ClosedXML_Tests/Excel/Misc/StylesTests.cs

(_edit Francois_) Addresses #797 , but does not completely close it. We should still provide a stripped down version of dumping data with minimal type checking, probably in a new `InsertXXX` method.

Remove the dependency on FastMember. Improve performance of InsertData (#797)

---

ClosedXML/Excel/Caching/XLRepositoryBase.cs
ClosedXML/Excel/Cells/XLCell.cs
ClosedXML/Excel/Cells/XLCellsCollection.cs
ClosedXML/Excel/Columns/XLColumns.cs
ClosedXML/Excel/ConditionalFormats/Save/XLCFColorScaleConverter.cs
ClosedXML/Excel/Drawings/XLPicture.cs
ClosedXML/Excel/PageSetup/XLHFItem.cs
ClosedXML/Excel/PageSetup/XLHeaderFooter.cs
ClosedXML/Excel/PivotTables/PivotStyleFormats/XLPivotStyleFormats.cs
ClosedXML/Excel/Ranges/XLRangeBase.cs
ClosedXML/Excel/Ranges/XLRanges.cs
ClosedXML/Excel/Rows/XLRowCollection.cs
ClosedXML/Excel/Rows/XLRows.cs
ClosedXML/Excel/Sparkline/XLSparkLineGroup.cs
ClosedXML/Excel/Tables/XLTable.cs
ClosedXML/Excel/Tables/XLTables.cs
ClosedXML/Excel/XLWorkbook_Load.cs
ClosedXML/Excel/XLWorkbook_Save.NestedTypes.cs
ClosedXML/Excel/XLWorkbook_Save.cs
ClosedXML/Excel/XLWorksheet.cs
ClosedXML/Excel/XLWorksheets.cs
ClosedXML/Utils/OpenXmlHelper.cs

Hopefully this makes some small performance gain.
Firstly I remove a redundant `Add` call in `XLSparkLineGroup`
Then, I try to replace all `Dictionary.ContainsKey` + indexer with `TryGetValue`

Replace ContainsKey with TryGetValue

---

ClosedXML/Excel/Columns/XLColumn.cs
ClosedXML/Excel/Rows/XLRow.cs
ClosedXML/Excel/XLWorksheet.cs
ClosedXML_Tests/Excel/Ranges/UsedAndUnusedCellsTests.cs

Fixes #1367 . 
Regression was in 226a1c8689b0eed3fa5d7b5c5af9651fef8b5b29
`.CellsUsed()` should return only cells with content. Cells without content, but with formatting should not be returned here.

.CellsUsed() should return only cells with content. 

---

ClosedXML/Excel/CalcEngine/CalcEngineHelpers.cs
ClosedXML/Excel/CalcEngine/Functions/MathTrig.cs
ClosedXML/Excel/CalcEngine/Functions/Statistical.cs
ClosedXML/Excel/CalcEngine/Functions/Tally.cs
ClosedXML_Sandbox/PerformanceRunner.cs
ClosedXML_Tests/Excel/CalcEngine/StatisticalTests.cs

Fixes #1431 
Follow Excel's convention of equality, i.e.  `1 != true`, but `3 == "3"`. LibreOffice treats them the alternative way.

Fix treatment of SUMIF and COUNTIF for mixed data

---

ClosedXML/Excel/XLWorksheet.cs
ClosedXML_Tests/Excel/Ranges/UsedAndUnusedCellsTests.cs

Same as #1445, targeting `release-candidate` branch
(cherry picked from commit 60a7903facd07a0618ea194ef86f2b97c86201e4)

Fix the incorrect FirstRowUsed method (#1443), RC branch

---

ClosedXML/Excel/Cells/XLCell.cs
ClosedXML/Extensions/TypeExtensions.cs
ClosedXML_Tests/Excel/Cells/XLCellTests.cs

Fixes #1430 
Enables 2 functionalities:
- Nullables: `IXLCell.TryGetValue<double?>(out double? value)` and `IXLCell.GetValue<double?>()`
- Enums:  `IXLCell.TryGetValue<MyEnum>(out MyEnum value)` and `IXLCell.GetValue<MyEnum>()`

Better nullable and enum support

---

.editorconfig
ClosedXML/Excel/CalcEngine/CalcEngineHelpers.cs
ClosedXML/Excel/CalcEngine/Functions/MathTrig.cs
ClosedXML/Excel/CalcEngine/Functions/XLMath.cs
ClosedXML/Excel/Cells/XLCell.cs
ClosedXML/XLHelper.cs
ClosedXML_Tests/Excel/Ranges/MergedRangesTests.cs

Replaced `str == ""` and `str == string.Empty` 
with `str.Length == 0`
+it will increase perfomance a little bit
-perhaps it is less readable
Also I added 
```
dotnet_diagnostic.CA1820.severity = error
```
to avoid using `str == ""` in the future
___
Here is benchmark results for `str == ""` vs `str.Length == 0`
``` ini
.NET Core SDK=3.1.300
[Host]     : .NET Core 3.1.4 (CoreCLR 4.700.20.20201, CoreFX 4.700.20.22101), X64 RyuJIT
DefaultJob : .NET Core 3.1.4 (CoreCLR 4.700.20.20201, CoreFX 4.700.20.22101), X64 RyuJIT
```
|                          Method |            Mean |         Error |        StdDev |
|-------------------------------- |----------------:|--------------:|--------------:|
| Test_1_000_000_EqualityOperator | 15,394,460.9 ns | 302,780.33 ns | 488,933.80 ns |
| …

Test for empty strings using string length

---

ClosedXML/Excel/XLWorkbook_Save.cs

Tried to solve problem with comparing doubles to doubles using  `== `
Changed:
`left.Width.Value == right.Width.Value))`
to
`(Math.Abs(left.Width.Value - right.Width.Value) < tolerance)))`
with tolerance = 1e-10;

fix an odd precise comparison

---

ClosedXML/Excel/Cells/XLCell.cs
ClosedXML_Tests/Excel/Cells/XLCellTests.cs

Fixes #1469 
Make `TryGetValue` try harder to coerce between data types.

IXLCell.TryGetValue improvements

---

ClosedXML/ClosedXML.csproj

Now CI fails every time without this change.
CI message - "The 'PackageIconUrl'/'iconUrl' element is deprecated. Consider using the 'PackageIcon'/'icon' element instead. Learn more at https://aka.ms/deprecateIconUrl"

Fix problem with deprecated nuget package url

---

ClosedXML/Utils/OpenXmlColorTypeAdapters.cs
ClosedXML/Utils/OpenXmlHelper.cs

Fixes #1281
Fixes #1494
Use adapter pattern (or is this a bridge?) instead of dynamic keyword.

Revert use of dynamic keyword to convert ColorType. 

---

ClosedXML/Excel/CalcEngine/CalcEngine.cs
ClosedXML/Excel/CalcEngine/XLCalcEngine.cs
ClosedXML_Tests/Excel/CalcEngine/CalcEngineExceptionTests.cs
ClosedXML_Tests/Excel/CalcEngine/MathTrigTests.cs

We were throwing inappropriate exceptions for a cell formula e.g. `=XXX`.

Throw appropriate NameNotRecognizedException when unknown identifier is found

---

ClosedXML/Excel/DataValidation/XLDataValidations.cs
ClosedXML_Tests/Excel/Saving/SavingTests.cs

XLDataValidations.ProcessRangeRemoved () throws a NullReferenceException when adding a row above a cell that has data validation set.
As a solution, I added a null check.

add null check to ProcessRangeRemoved

---

.gitignore
ClosedXML/ClosedXML.csproj

I started to use Rider some time ago but was not able to use it with ClosedXML as there were some strange exceptions on build.
```
Microsoft.Build.Tasks.Git.targets(20, 5): [MSB4018] The "Microsoft.Build.Tasks.Git.LocateRepository" task failed unexpectedly.
System.TypeInitializationException: The type initializer for 'Microsoft.Build.Tasks.Git.TaskImplementation' threw an exception.
---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build.Tasks.Git, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
File name: 'Microsoft.Build.Tasks.Git, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build.Tasks.Git, …
```

Upgrade libraries that do not work well in Rider

---

ClosedXML/Excel/CalcEngine/Expression.cs
ClosedXML_Tests/Excel/CalcEngine/TextTests.cs

Ensure EmptyValueExpression evaluates to null by setting internal token to a LITERAL token type with value null.

Ensure EmptyValueExpression evaluates to null

---

ClosedXML/Excel/XLWorksheet.cs
ClosedXML/XLHelper.cs
ClosedXML/XLHelper_ASF.cs
ClosedXML_Tests/Excel/Worksheets/XLWorksheetTests.cs
ClosedXML_Tests/XLHelperTests.cs

Added CreateSafeSheetName method to **XLHelper** class.
Creates a valid sheet name, which is conform to the rules:
- minimum length is 1
- maximum length is 31
- doesn't contain special chars: : 0x0000, 0x0003, / \ ? * ] [
- Sheet names must not begin or end with ' (apostrophe)
- never null
Fixes #1456

#1456 Add CreateSafeSheetName method

---

ClosedXML/Excel/Cells/XLCell.cs
ClosedXML/Excel/Cells/XLCellsCollection.cs
ClosedXML/Excel/InsertData/ArrayReader.cs
ClosedXML/Excel/InsertData/DataRecordReader.cs
ClosedXML/Excel/InsertData/DataTableReader.cs
ClosedXML/Excel/InsertData/IInsertDataReader.cs
ClosedXML/Excel/InsertData/InsertDataReaderFactory.cs
ClosedXML/Excel/InsertData/NullDataReader.cs
ClosedXML/Excel/InsertData/ObjectReader.cs
ClosedXML/Excel/InsertData/SimpleNullableTypeReader.cs
ClosedXML/Excel/InsertData/SimpleTypeReader.cs
ClosedXML/Excel/InsertData/UntypedObjectReader.cs
ClosedXML/Excel/Tables/XLTableField.cs
ClosedXML/Excel/XLWorksheet.cs
ClosedXML/Extensions/EnumerableExtensions.cs
ClosedXML/Extensions/ReflectionExtensions.cs
ClosedXML_Tests/ClosedXML_Tests.csproj
ClosedXML_Tests/Excel/InsertData/ArrayTypeReaderTests.cs
ClosedXML_Tests/Excel/InsertData/DataRecordReaderTests.cs
ClosedXML_Tests/Excel/InsertData/DataRowReaderTests.cs
ClosedXML_Tests/Excel/InsertData/InsertDataReaderFactoryTests.cs
ClosedXML_Tests/Excel/InsertData/ObjectReaderTests.cs
ClosedXML_Tests/Excel/InsertData/SimpleNullableTypeReaderTests.cs
ClosedXML_Tests/Excel/InsertData/SimpleTypeReaderTests.cs
ClosedXML_Tests/Excel/InsertData/UntypedObjectReaderTests.cs
ClosedXML_Tests/Excel/Tables/TablesTests.cs
ClosedXML_Tests/Extensions/EnumerableExtensionsTests.cs
ClosedXML_Tests/Extensions/ReflectionExtensionTests.cs

It is a continuation of #1388. It does not improve performance very much but, in my opinion, makes `InsertDataInternal` method much easier to understand and to extend, if we need it in the future.
Also, it fixes #1479 and adds support for collections of nullable structs as a table source.

Refactoring of InsertData logic (#797)

---

ClosedXML/Excel/Columns/XLColumns.cs
ClosedXML/Excel/Rows/XLRows.cs
ClosedXML/Excel/XLWorksheet.cs

Fixes #1482 
Benchmark:
```
var number = 1000;
for (int i = 0; i < 10; i++)
{
using var ms = new MemoryStream();
var data = Enumerable.Range(0, number).Select(i => Guid.NewGuid());
var wb = new XLWorkbook();
wb.AddWorksheet().FirstCell().InsertData(data);
wb.SaveAs(ms);
using var workBook = new XLWorkbook(ms);
var sw = new Stopwatch();
sw.Start();
var worksheet = workBook.Worksheets.ElementAt(0);
var row = worksheet.Rows().ElementAt(1);
var cell = row.Cell(1).Value?.ToString().Trim();
Console.WriteLine($"{number}\t{sw.ElapsedMilliseconds}");
number *= 2;
}
```
Output:
```
1000    3
2000    3
4000    10
8000    42
16000   174
32000   757
64000   2759
128000  10737
256000  45718
512000  188466
```

Improve Rows() method performance (#1482)

---

ClosedXML_Examples/ClosedXML_Examples.csproj
ClosedXML_Sandbox/ClosedXML_Sandbox.csproj

@Pankraty Any objections? Seems like a default VS2019 installation doesn't include `netcoreapp2.x` anymore.

Upgrade netcoreapp2.0 to netcoreapp3.1 in Sandbox and Examples

---

ClosedXML/Utils/ColorStringParser.cs

Many hex codes didn't have a `#`, especially when dealing with sparklines. This caused an exception, which was caught and subsequent color code parsing dealt with it successfully. But adding the `#` if it's omitted should result it a performance gain with colour code parsing.

Before attempting to parse colour code, add hash before RGBA hex code if it doesn't exist

---

ClosedXML.Tests/Excel/NamedRanges/NamedRangesTests.cs
ClosedXML/Excel/CalcEngine/CalcEngine.cs
ClosedXML/Excel/CalcEngine/Token.cs

This solves 2 issues:
- Boolean parameters were parsed as identifiers and only parsed to Boolean values during evaluation. This now changes it to parse Boolean literal value tokens when the expression is parsed.
- Peeks ahead for `(` token to distinguish between named ranges and functions, e.g. `=RAND * 10` vs `=RAND() * 10`.

Avoid confusion between named ranges and functions with same name

---

ClosedXML.Examples/ClosedXML.Examples.csproj
ClosedXML.Sandbox/ClosedXML.Sandbox.csproj
ClosedXML.Sandbox/ReflectionExtensions.cs
ClosedXML.Tests/ClosedXML.Tests.csproj
ClosedXML.Tests/Excel/Misc/XLWorkbookTests.cs
ClosedXML.Tests/OleDb/OleDbTests.cs
ClosedXML/ClosedXML.csproj
ClosedXML/Excel/Drawings/XLPicture.cs
ClosedXML/Excel/Style/Colors/XLColor_Static.cs
ClosedXML/Excel/Style/XLBorder.cs
ClosedXML/Excel/XLWorkbook.cs
ClosedXML/Excel/XLWorksheetInternals.cs
ClosedXML/XLHelper.cs

The .NET SDK already provides target framework [preprocessor symbols](https://docs.microsoft.com/en-us/dotnet/standard/frameworks#how-to-specify-a-target-framework), there is no need to define additional ones.
Also, it's 2022 so the commented out code that says "keeping it around for in case we bring back .NET3.5 support" has been removed.

Remove the custom preprocessor symbols

---

ClosedXML.Tests/Excel/CalcEngine/MathTrigTests.cs
ClosedXML.Tests/Excel/Cells/XLCellTests.cs

Some languages, e.g czech one have a separator of digits different than period (they might have a comma instead). Formulas must be in culture invariant grammar and string-to-number conversion is using current culture.

Fix unit test culture errors

---

ClosedXML.Tests/Utils/PackageHelper.cs
ClosedXML.Tests/Utils/StreamHelper.cs

Compare two XML files using XML structure and not a string. The key issue for this is that DocumentFormat.OpenXml was generating attribtues in a different order. Also, regexp are seriously not a good to manipulate xml (or any other nonregular language).

Xml compare
