ClosedXML/ClosedXML

ClosedXML/ClosedXML/ClosedXML/Excel/XLWorkbook_Load.cs
from CodePlex https://closedxml.codeplex.com/SourceControl/network/forks/gibsoon/ClosedXML/contribution/8764
=> Check returned value is null when no worksheet was found.

ClosedXML/ClosedXML/ClosedXML_Tests/ClosedXML_Tests.csproj, ClosedXML/ClosedXML/ClosedXML_Tests/Excel/RichText/XLRichStringTests.cs, ClosedXML/ClosedXML/ClosedXML_Tests/packages.config
Can now run tests inside Visual Studio. 
PS: Are there any reasons NOT to upgrade to NUnit 3?
=> Upgrade NUnit to version 3.4.1

ClosedXML/Excel/CalcEngine/Functions/Text.cs, ClosedXML_Tests/Excel/CalcEngine/FunctionsTests.cs, ClosedXML_Tests/Excel/CalcEngine/TextTests.cs
Add unit tests for all text functions and fix broken / incorrect functions.
Fixes #8 .
=> Text function fixes

ClosedXML/ClosedXML.csproj, ClosedXML/Excel/CalcEngine/CalcEngine.cs, ClosedXML/Excel/CalcEngine/Expression.cs, ClosedXML/Excel/CalcEngine/Functions/Lookup.cs, ClosedXML/Excel/Ranges/IXLRange.cs, ClosedXML/Excel/Ranges/XLRange.cs, ClosedXML_Net3.5/ClosedXML_Net3.5.csproj, ClosedXML_Tests/ClosedXML_Tests.csproj, ClosedXML_Tests/Excel/CalcEngine/LookupTests.cs
Implement VLOOKUP and HLOOKUP.
Bring `develop` up to date with `master` before merging this.
=> Implement VLOOKUP and HLOOKUP

ClosedXML/Excel/Tables/XLTable.cs, ClosedXML/Excel/Tables/XLTableField.cs, ClosedXML_Tests/Excel/Tables/TablesTests.cs
=> Issue55 load table with hidden header row

README.md
=> Include nuget install command  

ClosedXML/Excel/CalcEngine/Functions/DateAndTime.cs, ClosedXML_Tests/Excel/CalcEngine/DateAndTimeTests.cs
I rearranged the DateAndTime class too so that all functions are in alphabetical order.
=> Implement all date and time functions

ClosedXML/Excel/CalcEngine/Expression.cs, ClosedXML/Excel/CalcEngine/Functions/Lookup.cs, ClosedXML_Tests/Excel/CalcEngine/LogicalTests.cs, ClosedXML_Tests/Excel/Misc/FormulaTests.cs
=> Catch implicit conversion that fails. 

ClosedXML/Excel/PageSetup/XLPageSetup.cs, ClosedXML/Excel/XLWorksheet.cs, ClosedXML_Tests/ClosedXML_Tests.csproj, ClosedXML_Tests/Excel/PageSetup/PageBreaksTests.cs
=> Shift page breaks

ClosedXML/ClosedXML.csproj, ClosedXML/Excel/CalcEngine/CalcEngineHelpers.cs, ClosedXML/Excel/CalcEngine/Functions/MathTrig.cs, ClosedXML/Excel/CalcEngine/Functions/Statistical.cs, ClosedXML/Excel/CalcEngine/Functions/Tally.cs, ClosedXML_Net3.5/ClosedXML_Net3.5.csproj, ClosedXML_Tests/ClosedXML_Tests.csproj, ClosedXML_Tests/Excel/CalcEngine/FunctionsTests.cs, ClosedXML_Tests/Excel/CalcEngine/StatisticalTests.cs
Fix some maths and statistical functions. Add statistical functions unit tests.
Fixes #150
=> Fix maths / statistical functions

ClosedXML/Excel/XLWorkbook_Save.cs
=> Remove orphaned drawings from worksheets

ClosedXML/Excel/Cells/XLCell.cs, ClosedXML/Excel/Comments/XLComment.cs, ClosedXML/Excel/Ranges/XLRangeBase.cs, ClosedXML_Tests/Excel/Ranges/InsertingRangesTests.cs
Don't reference cell to get row height - it will create new unused cell in cells collection.
Fixes #213
=> Don't reference cell to get row height

ClosedXML/Excel/CalcEngine/Functions/Text.cs, ClosedXML_Tests/Excel/CalcEngine/TextTests.cs
=> Text() function - return string as is if input value is already a string

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, ClosedXML.sln
Add templates for issues and pull requests
fixes #251
=> Add issue and pull request templates

ClosedXML/Excel/XLWorkbook.cs
=> Support xltm and xltx files

ClosedXML/Excel/Cells/XLCell.cs, ClosedXML/XLHelper.cs, ClosedXML_Tests/Excel/Cells/XLCellTests.cs
=> Check OADate range before parsing. Return string if parsing fails.

ClosedXML/ClosedXML.csproj, ClosedXML/Excel/Drawings/XLPicture.cs, ClosedXML/Excel/IXLWorksheet.cs, ClosedXML/Excel/XLWorkbook_ImageHandling.cs, ClosedXML/Excel/XLWorkbook_Load.cs, ClosedXML/Excel/XLWorkbook_Save.cs, ClosedXML/Excel/XLWorksheet.cs, ClosedXML/Extensions/OpenXmlPartContainerExtensions.cs, ClosedXML_Tests/Excel/ImageHandling/PictureTests.cs, ClosedXML_Tests/Excel/Loading/LoadingTests.cs
Update @bsermon 's changes for new API. Closes #319
=> Load and copy images

ClosedXML/Excel/CalcEngine/Functions/MathTrig.cs, ClosedXML_Tests/Excel/CalcEngine/FunctionsTests.cs
It seemed easier to just create a new pull request since it was a couple small changes and I am not familiar enough with Git or GitHub to see how to best change the other one.  I figured you could just reject the other pull request and this one will hopefully be nice and easy and build successfully!  :)
Thanks!
- Is there a blog post?
- Does the knowledge base need an update?
- Does this add new (C#) dependencies?
=> Edit Round function in MathTrig.cs develop branch

ClosedXML/Excel/XLWorksheets.cs, ClosedXML_Tests/Excel/Worksheets/XLWorksheetTests.cs
=> Check for sheet name before adding. 

ClosedXML/Excel/XLWorkbook_Save.cs
=> Check for null when rebasing picture Ids

ClosedXML/Excel/XLWorkbook_Save.cs
=> Use longs to prevent overflow.

ClosedXML/Excel/XLWorkbook_Save.cs
Re-position stream to start (0)
Bug fix 
positioning stream to 0 fixes ref id errors
- Is there a blog post?
- Does the knowledge base need an update?
- Does this add new (C#) dependencies?
=> Bug Fix when saving same image multiple times

ClosedXML/Excel/Columns/XLColumn.cs, ClosedXML/Excel/Ranges/IXLRangeBase.cs, ClosedXML/Excel/Ranges/XLRangeBase.cs, ClosedXML/Excel/Rows/IXLRow.cs, ClosedXML/Excel/Rows/XLRow.cs, ClosedXML/Excel/XLWorksheet.cs, ClosedXML_Tests/Excel/Rows/RowTests.cs
Fixes #352 .
Merge #402 first.
=> Clear row height

ClosedXML/Excel/CalcEngine/CalcEngine.cs, ClosedXML/Excel/CalcEngine/Functions/MathTrig.cs, ClosedXML_Tests/ClosedXML_Tests.csproj, ClosedXML_Tests/Excel/CalcEngine/MathTrigTests.cs
=> Fully implement FLOOR function

ClosedXML/Excel/Cells/XLCell.cs, ClosedXML/Excel/Tables/XLTable.cs, ClosedXML/Excel/Tables/XLTableField.cs, ClosedXML_Tests/Excel/Tables/TablesTests.cs
=> Update table fieldnames by setting cell values

ClosedXML/Excel/CalcEngine/CalcEngine.cs, ClosedXML/Excel/CalcEngine/Expression.cs, ClosedXML/Excel/CalcEngine/Functions/MathTrig.cs, ClosedXML_Tests/ClosedXML_Tests.csproj, ClosedXML_Tests/Excel/CalcEngine/MathTrigTests.cs
=> Support functions with period

ClosedXML/Excel/XLWorkbook_Save.cs, ClosedXML_Tests/Excel/Saving/SavingTests.cs
=> Clear list of deleted worksheets after save

ClosedXML/Excel/CalcEngine/Functions/Lookup.cs, ClosedXML_Tests/Excel/CalcEngine/LookupTests.cs
=> Default range lookup to true if parameter is EmptyValueExpression

ClosedXML/Excel/XLWorksheets.cs, ClosedXML_Tests/Excel/Worksheets/XLWorksheetTests.cs
=> Allow rename of sheet by changing case

ClosedXML/Excel/XLWorkbook_Save.cs, ClosedXML_Tests/Excel/Worksheets/XLWorksheetTests.cs
=> Set sheet state to null if it's visible.

ClosedXML/Excel/Cells/XLCell.cs, ClosedXML/Excel/Coordinates/IXLAddress.cs, ClosedXML/Excel/Coordinates/XLAddress.cs, ClosedXML/Excel/Hyperlinks/XLHyperlink_Internal.cs, ClosedXML/Excel/Ranges/IXLRangeAddress.cs, ClosedXML/Excel/Ranges/XLRangeAddress.cs, ClosedXML_Tests/ClosedXML_Tests.csproj, ClosedXML_Tests/Excel/Coordinates/XLAddressTests.cs, ClosedXML_Tests/Excel/Misc/HyperlinkTests.cs, ClosedXML_Tests/Excel/Ranges/XLRangeAddressTests.cs
=> Fix hyperlinks - include sheet name.

ClosedXML/ClosedXML.csproj, ClosedXML/Excel/Style/XLPredefinedFormat.cs
Adds a reference point for number formats available.
No need to lookup ids/codes on the Internet. Closes #478.
ClosedXML/Excel/Style/XLFormatIds.cs directly
n/a
n/a
- Is there a blog post? NO
- Does the knowledge base need an update? YES, in particular this https://github.com/closedxml/closedxml/wiki/NumberFormatId-Lookup-Table
- Does this add new (C#) dependencies? NO
=> Adds a reference point for number formats available.

ClosedXML/Excel/Drawings/XLPicture.cs, ClosedXML_Tests/Excel/ImageHandling/PictureTests.cs
=> Set picture Id correctly

ClosedXML/Excel/Cells/IXLCell.cs, ClosedXML/Excel/Cells/XLCell.cs, ClosedXML_Tests/Excel/Cells/XLCellTests.cs
=> Implement IXLCell.CurrentRegion

ClosedXML/Excel/CalcEngine/Functions/MathTrig.cs, ClosedXML_Tests/Excel/CalcEngine/MathTrigTests.cs
=> Implement SUMPRODUCT

ClosedXML/Excel/XLWorkbook_Save.cs
=> Small adjustments for when pivot table classic layout is selected.

ClosedXML/Excel/AutoFilters/IXLBaseAutoFilter.cs, ClosedXML/Excel/Ranges/IXLRangeBase.cs, ClosedXML/Excel/Ranges/XLRangeBase.cs, ClosedXML_Examples/Misc/AutoFilter.cs, ClosedXML_Tests/Excel/AutoFilters/AutoFilterTests.cs
=> Clear AutoFilter by calling SetAutoFilter(false)

ClosedXML/Excel/Cells/XLCell.cs, ClosedXML_Tests/Excel/Tables/TablesTests.cs
=> Prevent adding of empty data table (no columns)

ClosedXML/Excel/PivotTables/IXLPivotTable.cs, ClosedXML/Excel/PivotTables/PivotValues/XLPivotValues.cs, ClosedXML/Excel/PivotTables/XLPivotFields.cs, ClosedXML/Excel/PivotTables/XLPivotTable.cs
=> Check pivot table source range headers before adding field / value

ClosedXML/Excel/Cells/XLCell.cs, ClosedXML/Excel/Ranges/XLRanges.cs
Improved performance of some methods.
=> Improved performance of some methods.

ClosedXML/Excel/XLWorkbook_Save.cs
=> Check pivot cache definition worksheet source not is null.

ClosedXML/Excel/CalcEngine/Functions/MathTrig.cs, ClosedXML_Tests/Excel/CalcEngine/MathTrigTests.cs
implements DECIMAL and corresponding unit tests.
code isn't that big, so shouldn't matter.
no blogpost,
no knowledge base update necessary,
no new dependencies
=> #52: implement DECIMAL function

ClosedXML/Excel/XLWorkbook_Load.cs
=> Apply upper and lower bounds to picture marker

ClosedXML/Excel/CalcEngine/Functions/MathTrig.cs, ClosedXML_Tests/Excel/CalcEngine/MathTrigTests.cs
implements the Excel function COT, which is the co tangens.
Adds tests for it.
as before: PR is quite small, so should be straight forward.
If it feels necessary, compare what Excel does on cell content =COT(x) for any X and what's the result of the function implemented.
Mathmatically there are special cases for any multiple of π as for these values the result is not defined (these are poles with a local limit of +infinity or -infinity, depending on the direction one comes from).
Therefore these are in fact special cases but I have no idea how to cover that by unit tests as PI is impossible to model correct.
Exception: 0 = 0*π is one of these special cases, that case is covered by test.
=> implement COT function (co-tangens) and corresponding tests

ClosedXML/Excel/XLWorkbook.cs, ClosedXML/Excel/XLWorksheets.cs, ClosedXML_Tests/Excel/Worksheets/XLWorksheetTests.cs
=> Case insensitive IXLWorksheets.TryGetWorksheet

ClosedXML/Excel/XLWorkbook.cs, ClosedXML/Excel/XLWorksheet.cs, ClosedXML_Tests/Excel/AutoFilters/AutoFilterTests.cs
=>  Copy autofilter to new worksheet correctly

ClosedXML/Excel/CalcEngine/Functions/MathTrig.cs, ClosedXML_Tests/Excel/CalcEngine/MathTrigTests.cs
implements the function and corresponding tests.
=> implement Excel function COMBINA in CalcEngine

ClosedXML/Excel/Tables/XLTable.cs
=> Set table header row data type after setting private field

ClosedXML/Excel/CalcEngine/Functions/Lookup.cs, ClosedXML/Excel/CalcEngine/Functions/Text.cs, ClosedXML_Tests/Excel/CalcEngine/LookupTests.cs
=> Allow Hyperlink to have 1 to 2 parameters

ClosedXML/Excel/PageSetup/XLHeaderFooter.cs, ClosedXML_Tests/Excel/PageSetup/HeaderFooterTests.cs
=> Fix header/footer parsing. 

ClosedXML/Excel/XLWorksheet.cs
In some cases I received an OutOfMemotyException. As it turned out in the methods ShiftConditionalFormattingRows and ShiftConditionalFormattingColumns there is code
`
ConditionalFormats.Where (cf => cf.Range.Intersects(cellModel.AsRange)).ToList()
`
Here in the cycle, a Range is created, which is not destroyed.
=> OutOfMemoryException. Some range disposing.

ClosedXML/Excel/CalcEngine/Functions/MathTrig.cs, ClosedXML/Excel/CalcEngine/Functions/XLMath.cs, ClosedXML_Tests/Excel/CalcEngine/MathTrigTests.cs
Adds missing functions and completes unit tests.
Functions and unit tests added for:
- ARABIC
- BASE
Fixed functions and added unit tests for:
- ACOS
- ACOSH
- ASIN
- ATAN2
- ATANH
Unit tests only added for already existing functions:
- ABS
- ASINH
- ATAN
I tried to work on one function per commit, although in some cases I needed a second one later.
Perhaps best is to go through the MathTrigTests.cs file and look up corresponding functions for their implementation (if new - ARABIC and BASE) or the changes withing (ACOS, ACOSH, ASIN, ATAN2, ATANH). For ABS, ASINH and ATAN there are new unit tests only.
Compare with how Excel behaves for the same functionality.
=> Add all missing functions starting with A and B, except AGGREGATE

ClosedXML/Excel/XLWorkbook_Save.cs
=> Remove pageSetup.copies attribute if it's 0

ClosedXML/Excel/XLWorkbook_Save.cs
=> Improve pivot table saving by looking only at cells used.

ClosedXML/ClosedXML.csproj, ClosedXML/Excel/CalcEngine/Expression.cs, ClosedXML/Excel/CalcEngine/Functions/Text.cs, ClosedXML/Excel/Cells/XLCell.cs, ClosedXML/Extensions/FormatExtensions.cs, ClosedXML/packages.config, ClosedXML_Tests/Excel/CalcEngine/TextTests.cs, ClosedXML_Tests/Excel/Styles/NumberFormatTests.cs
=> Use ExcelNumberFormat library to format strings.

ClosedXML/Excel/XLWorkbook_Load.cs, ClosedXML/Utils/XmlEncoder.cs, ClosedXML_Tests/Excel/Saving/SavingTests.cs
=> Correctly escape xHHHH when saving

ClosedXML/Excel/XLWorkbook_Load.cs
=> Ignore custom property with no name.

ClosedXML/Excel/Cells/XLCell.cs, ClosedXML_Tests/Excel/Cells/XLCellTests.cs
=> Return 0 when referencing empty cell directly

ClosedXML/Excel/XLWorkbook.cs
=> Fix XLWorkbook.ToString() for new instances

ClosedXML/Excel/XLWorkbook.cs, ClosedXML_Tests/Excel/Saving/SavingTests.cs
=> Fix. Failed to "SaveAs" a file with a ReadOnly attribute

ClosedXML/Excel/ConditionalFormats/IXLConditionalFormat.cs, ClosedXML/Excel/ConditionalFormats/Save/XLCFBaseConverter.cs, ClosedXML/Excel/ConditionalFormats/XLConditionalFormat.cs, ClosedXML/Excel/XLWorkbook_Load.cs, ClosedXML_Examples/ConditionalFormatting/ConditionalFormatting.cs
=> Refactor IXLConditionalFormat StopIfTrue

ClosedXML/ClosedXML.csproj, ClosedXML/Excel/Cells/XLCell.cs, ClosedXML/packages.config, ClosedXML_Examples/ClosedXML_Examples.csproj, ClosedXML_Examples/app.config, ClosedXML_Examples/packages.config, ClosedXML_Sandbox/ClosedXML_Sandbox.csproj, ClosedXML_Sandbox/PerformanceRunner.cs, ClosedXML_Sandbox/app.config, ClosedXML_Sandbox/packages.config
Related pull request #650, #659 
Deep thanks to everyone for the help! I finally did it )
=> Change target framework to 4.0

ClosedXML/Excel/XLWorkbook_Load.cs
=> Upper and lower limits on row and column numbers 

ClosedXML/Excel/XLWSContentManager.cs, ClosedXML/Excel/XLWorkbook_Save.cs, ClosedXML_Tests/Excel/Saving/SavingTests.cs
=> Set context correctly after saving drawings

ClosedXML/Excel/PivotTables/PivotValues/XLPivotValues.cs, ClosedXML/Excel/Tables/XLTable.cs, ClosedXML/Excel/XLWorkbook.cs, ClosedXML/Excel/XLWorkbook_Load.cs, ClosedXML/Excel/XLWorkbook_Save.cs, ClosedXML/Utils/OpenXmlHelper.cs
=> Linq improvements by mafii

ClosedXML/Excel/Tables/XLTableField.cs, ClosedXML/Excel/XLWorkbook.cs, ClosedXML/Excel/XLWorkbook_Save.cs
=> Disable events while saving

ClosedXML/Excel/CalcEngine/CalcEngineHelpers.cs, ClosedXML/Excel/CalcEngine/Functions/MathTrig.cs, ClosedXML_Tests/Excel/CalcEngine/MathTrigTests.cs
=> Fix expected order of SUMIFS parameters. 

ClosedXML/Excel/ConditionalFormats/Save/XLCFColorScaleConverter.cs
=> Fix XLCFColorScaleConverter for indexed and theme colors

ClosedXML/Excel/Columns/XLColumn.cs, ClosedXML/Excel/Ranges/IXLRangeAddress.cs, ClosedXML/Excel/Ranges/XLRangeAddress.cs, ClosedXML/Excel/Ranges/XLRangeBase.cs, ClosedXML/Excel/Ranges/XLRanges.cs, ClosedXML/Excel/Rows/XLRow.cs, ClosedXML/Excel/XLWorksheet.cs, ClosedXML/XLHelper.cs, ClosedXML_Tests/Excel/AutoFilters/AutoFilterTests.cs, ClosedXML_Tests/Excel/Columns/ColumnTests.cs, ClosedXML_Tests/Excel/Ranges/InsertingRangesTests.cs, ClosedXML_Tests/Excel/Rows/RowTests.cs
Refactor IsInvalid to IsValid
Remove public setter from IXLRangeAddress.IsValid
=> Refactor IsInvalid to IsValid

ClosedXML/Excel/CalcEngine/XLCalcEngine.cs, ClosedXML/Excel/Cells/XLCell.cs, ClosedXML_Tests/Excel/Cells/XLCellTests.cs
=> IsEvaluating flag added to XLCell

ClosedXML/Excel/Cells/IXLCell.cs, ClosedXML/Excel/Cells/XLCell.cs, ClosedXML_Tests/Excel/Worksheets/XLWorksheetTests.cs
=> Add IXLCell.MergedRange()

ClosedXML/Excel/Cells/XLCell.cs, ClosedXML_Tests/Excel/Cells/XLCellTests.cs
=> Implement IsEvaluating flag for simple/direct formula evaluation too.

ClosedXML/Excel/PivotTables/XLPivotField.cs
Breaking change, but should not affect many, if any at all.
=> Make XLPivotField internal

ClosedXML/Excel/IXLWorksheets.cs, ClosedXML/Excel/Tables/XLTable.cs, ClosedXML/Excel/Tables/XLTableField.cs, ClosedXML/Excel/XLWorkbook_Save.cs, ClosedXML/Excel/XLWorksheet.cs, ClosedXML_Tests/Excel/Tables/TablesTests.cs
- Ensure correct totals row formula format for fields with spaces, single quotes and hashes
- Make table names case insensitive
=> Ensure correct totals row formula format for fields with spaces, single quotes and hashes

ClosedXML/Excel/Tables/XLTable.cs, ClosedXML_Tests/Excel/Tables/TablesTests.cs
=> Throw ArgumentException when attempting to create overlapping tables.

ClosedXML/Excel/AutoFilters/XLAutoFilter.cs, ClosedXML/Excel/CalcEngine/Functions/Tally.cs, ClosedXML/Excel/CalcEngine/Functions/XLMath.cs, ClosedXML/Excel/Cells/XLCell.cs, ClosedXML/Excel/ConditionalFormats/Save/XLCFCellIsConverter.cs, ClosedXML/Excel/DataValidation/IXLDataValidation.cs, ClosedXML/Excel/DataValidation/IXLDataValidations.cs, ClosedXML/Excel/DataValidation/XLDataValidation.cs, ClosedXML/Excel/DataValidation/XLDataValidations.cs, ClosedXML/Excel/Drawings/XLPicture.cs, ClosedXML/Excel/Ranges/XLRange.cs, ClosedXML/Excel/Ranges/XLRangeAddress.cs, ClosedXML/Excel/Ranges/XLRanges.cs, ClosedXML/Excel/Rows/XLRow.cs, ClosedXML/Excel/Tables/IXLTableField.cs, ClosedXML/Excel/Tables/XLTable.cs, ClosedXML/Excel/Tables/XLTableField.cs, ClosedXML/Excel/XLWorkbook_Load.cs, ClosedXML/Excel/XLWorkbook_Save.cs, ClosedXML/Excel/XLWorksheet.cs, ClosedXML/XLHelper.cs
After I ran a code analysis tool I found a few issues - some are more important, others are less.
The obvious bug here is fixed with commit e9c22cec85cbc17ddbde31e526a0ffb35cb29676. Aside from this,  some checks were reorganized (removed, added or added), ```IDisposable``` implemented for classes containing disposable members, other small enhancements made.
=> Small bugfixes and improvements

ClosedXML/Excel/Cells/XLCell.cs, ClosedXML_Tests/Excel/Cells/XLCellTests.cs
=> More inline out parameters

ClosedXML/Excel/XLWorkbook_Save.cs, ClosedXML_Tests/ClosedXML_Tests.csproj, ClosedXML_Tests/Excel/Globalization/GlobalizationTests.cs
Change call .ToString() to .ToInvariantString() in save workbook.
=> Change call .ToString() to .ToInvariantString()

ClosedXML_Tests/Excel/Cells/DataTypeTests.cs
=> Add test for changing data type

ClosedXML/Excel/Ranges/XLRangeBase.cs, ClosedXML/Excel/Style/XLStylizedBase.cs, ClosedXML/Excel/XLWorkbook_Load.cs, ClosedXML/Excel/XLWorksheet.cs, ClosedXML/XLHelper.cs
Here are a few changes that improve the performance of the large file loading. On my test example, the load time decreased from 13 sec to 8.5 sec in Debug mode and from 10 sec to 6.5 sec in Release mode.
=> Workbook load optimizations

appveyor.yml
Deploy NuGet packages to AppVeyor NuGet feed.
=> Deploy to AppVeyor NuGet feed

ClosedXML/Excel/CalcEngine/Exceptions/CalcEngineException.cs, ClosedXML/Excel/CalcEngine/Exceptions/CellReferenceException.cs, ClosedXML/Excel/CalcEngine/Exceptions/CellValueException.cs, ClosedXML/Excel/CalcEngine/Exceptions/DivisionByZeroException.cs, ClosedXML/Excel/CalcEngine/Exceptions/NameNotRecognizedException.cs, ClosedXML/Excel/CalcEngine/Exceptions/NoValueAvailableException.cs, ClosedXML/Excel/CalcEngine/Exceptions/NullValueException.cs, ClosedXML/Excel/CalcEngine/Exceptions/NumberException.cs
Fixes #896 
@Pankraty I think we should squeeze this in for 0.93, even though it's not a regression from 0.92. What do you think?
=> Make calculation engine exception public

ClosedXML/Excel/Cells/XLCell.cs, ClosedXML_Tests/Excel/Cells/XLCellTests.cs
=> Allow Guid values to be inserted

ClosedXML/Excel/XLWorkbook_Save.cs, ClosedXML_Tests/Excel/PivotTables/XLPivotTableTests.cs
Fixes problem with saving file multiple times. Pivot table relId has to be set after first save.
=> Fix pivot table integrity when saving multiple times.

ClosedXML/Excel/Cells/XLCell.cs, ClosedXML_Tests/Excel/Cells/XLCellTests.cs
Fixes #953 
@Pankraty We can consider your data type register later.
=> Add ability to set cell value to an enum value

ClosedXML/Excel/Tables/XLTable.cs, ClosedXML_Tests/Excel/Tables/TablesTests.cs
=> Allow table field names consisting of only whitespace

ClosedXML/Excel/Cells/XLCell.cs, ClosedXML_Tests/Excel/Cells/XLCellTests.cs
Fixes #1014 and hopefully improves performance (reduces number of string parsing attempts)
=> Improve XLCell.TryGetValue and implement additional tests

ClosedXML/Excel/Columns/XLColumn.cs, ClosedXML/Excel/Rows/XLRow.cs, ClosedXML_Tests/Excel/Worksheets/XLWorksheetTests.cs
=> Copy row/column visibility setting.

ClosedXML/XLHelper.cs
=> Lazy initialize graphics

ClosedXML/Excel/DataValidation/XLDataValidation.cs, ClosedXML_Tests/Excel/DataValidations/DataValidationTests.cs
Add check that data validation value length does not exceed 255 chars
Fixes #1016
=> Add check that data validation value length does not exceed 255 chars

ClosedXML/Excel/IXLWorksheet.cs, ClosedXML/Excel/XLWorkbook.cs, ClosedXML/Excel/XLWorksheet.cs, ClosedXML/Excel/XLWorksheets.cs, ClosedXML_Tests/Excel/AutoFilters/AutoFilterTests.cs
=> Remove IDisposable interface from IXLWorksheet

ClosedXML/Excel/DataValidation/IXLDataValidations.cs, ClosedXML/Excel/DataValidation/XLDataValidations.cs, ClosedXML/Excel/XLWorksheet.cs, ClosedXML/XLHelper.cs, ClosedXML_Tests/Excel/ConditionalFormats/ConditionalFormatShiftTests.cs, ClosedXML_Tests/Excel/DataValidations/DataValidationShiftTests.cs
=> Shift data validation ranges when inserting / delete ranges

ClosedXML/Excel/IXLFileSharing.cs, ClosedXML/Excel/IXLWorkbook.cs, ClosedXML/Excel/XLFileSharing.cs, ClosedXML/Excel/XLWorkbook.cs, ClosedXML/Excel/XLWorkbook_Load.cs, ClosedXML/Excel/XLWorkbook_Save.cs, ClosedXML_Tests/Excel/Misc/XLWorkbookTests.cs
Reference: https://docs.microsoft.com/en-us/dotnet/api/documentformat.openxml.spreadsheet.filesharing?view=openxml-2.8.1
I implemented only `ReadOnlyRecommended` and `UserName`. The other properties are about password hashing, which I'm not touching now.
=> Implement workbook FileSharing and a few of the properties

ClosedXML/Excel/Cells/XLCell.cs, ClosedXML/Excel/Ranges/XLRangeBase.cs, ClosedXML_Tests/Excel/ConditionalFormats/ConditionalFormatCopyTests.cs, ClosedXML_Tests/Excel/Ranges/CopyingRangesTests.cs
Supercedes #1092 
Closes #1092 
Closes #1091 
I made some small additions. I couldn't push this to your branch (don't know why), so I created a new PR.
=> Wrong worksheet for copied conditional formats fix

ClosedXML/Excel/Cells/XLCell.cs, ClosedXML_Tests/Excel/Cells/XLCellTests.cs
=> Add special case for inserting DBNull values

ClosedXML/Excel/Cells/XLCell.cs, ClosedXML/Excel/XLWorkbook_Load.cs, ClosedXML/Excel/XLWorkbook_Save.cs, ClosedXML_Tests/Excel/Styles/StyleTests.cs
=> Correctly save empty cell with quote prefix (do not treat as empty)

ClosedXML/Excel/IXLWorkbook.cs, ClosedXML/Excel/IXLWorksheets.cs, ClosedXML/Excel/XLWorkbook.cs, ClosedXML/Excel/XLWorksheets.cs, ClosedXML_Tests/Excel/Worksheets/XLWorksheetTests.cs
Add helper methods to add worksheet with default sheet name.
Solves https://stackoverflow.com/questions/54024621/add-blank-worksheet-to-workbook
=> Add helper methods to add worksheet with default sheet name

ClosedXML/Excel/CalcEngine/Functions/MathTrig.cs, ClosedXML_Tests/Excel/CalcEngine/MathTrigTests.cs
=>  Enhance TRUNC function for additional parameter

ClosedXML/Excel/XLWorksheets.cs, ClosedXML_Examples/Misc/AddingDataSet.cs, ClosedXML_Examples/Misc/AddingDataTableAsWorksheet.cs
=> Don't automatically adjust columns width to contents when inserting datatable. Some users want to opt out because of PlatformNotSupportedException

ClosedXML/Excel/XLWorkbook_Save.cs
=> Performance improvement to delete entire columns

ClosedXML/Excel/Cells/XLCell.cs, ClosedXML/Excel/Comments/XLComment.cs, ClosedXML/Excel/Drawings/Style/XLDrawingStyle.cs, ClosedXML_Tests/Excel/Comments/CommentsTests.cs
=> Copy comment style correctly when shifting ranges

ClosedXML/Excel/CalcEngine/CalcEngine.cs, ClosedXML/Excel/CalcEngine/CellRangeReference.cs, ClosedXML/Excel/CalcEngine/Functions/Text.cs, ClosedXML/Excel/CalcEngine/XLCalcEngine.cs, ClosedXML_Tests/Excel/CalcEngine/CalcEngineExceptionTests.cs, ClosedXML_Tests/Excel/CalcEngine/FunctionsTests.cs, ClosedXML_Tests/Excel/CalcEngine/TextTests.cs
=> Ignore default Excel function namespace and implement CONCAT function

ClosedXML/Excel/IXLSheetProtection.cs
Title says it all. Don't know why the setter was public at all.
=> Remove IXLSheetProtection.IsProtected public setter

CONTRIBUTING.md, README.md
First stab at adding developer guidelines.
=> Add developer guidelines

ClosedXML/Excel/CalcEngine/Functions/Lookup.cs, ClosedXML_Tests/Excel/CalcEngine/LookupTests.cs
Fixes #1218 
Did some CodeMaid reorganising too.
=> Implement MATCH and INDEX functions

ClosedXML/Excel/Cells/XLCell.cs, ClosedXML_Tests/Excel/Ranges/MergedRangesTests.cs
=> Merged ranges cell values should not be set, except for top left cell of merged range

ClosedXML/Excel/ConditionalFormats/Save/XLCFCellIsConverter.cs, ClosedXML_Tests/Excel/ConditionalFormats/ConditionalFormatTests.cs
Closes #1187 
Supersedes #1190
=> Fix the issue with conditional formats created in non-US culture (#1187)

ClosedXML/Excel/CalcEngine/Functions/Lookup.cs
As recommended by https://github.com/ClosedXML/ClosedXML/pull/1233#discussion_r293406426
=> Improve HLOOKUP and VLOOKUP performance

ClosedXML/Excel/Cells/XLCell.cs, ClosedXML_Tests/Excel/Misc/FormulaTests.cs
=> Fix a regular expression used for extracting A1 references

ClosedXML/Excel/Cells/XLCell.cs, ClosedXML_Tests/Excel/Cells/XLCellTests.cs
=> Fix evaluation of cells referring to themselves

ClosedXML_Tests/OleDb/OleDbTests.cs
Commit 2beb1c6da2e5379d459b71e729e9acc0c92fd336 in PR #794 broke this.
=> Fix broken OleDB tests

ClosedXML.vsmdi, ClosedXML_Tests/ClosedXML_Tests.csproj
Remove unused `MSTest` packages and obsolete `ClosedXML.vsmdi`
=> Remove unused test items

ClosedXML/XLHelper.cs, ClosedXML_Tests/Excel/Cells/XLCellTests.cs
=> Prevent int overflow with working with large TimeSpan values

ClosedXML/Excel/Cells/IXLCell.cs, ClosedXML/Excel/Cells/XLCell.cs, ClosedXML/Excel/XLWorkbook_Load.cs, ClosedXML_Tests/Excel/Globalization/GlobalizationTests.cs, ClosedXML_Tests/Excel/Loading/LoadingTests.cs, ClosedXML_Tests/Excel/Saving/SavingTests.cs
Remove obsolete `IXLCell.ValueCached`
Target for 0.96 or maybe later?
=> Remove obsolete IXLCell.ValueCached

ClosedXML/Excel/CalcEngine/CellRangeReference.cs, ClosedXML/Excel/CalcEngine/Expression.cs, ClosedXML_Tests/Excel/CalcEngine/CalcEngineCellEnumerationTests.cs
=> IEnumerator improvements - avoid evaluation of empty sheets

ClosedXML/Excel/Cells/XLCell.cs, ClosedXML_Sandbox/PerformanceRunner.cs, ClosedXML_Tests/Excel/Cells/XLCellTests.cs
=> Support IEnumerable for IXLCell.SetValue()

ClosedXML/Excel/CalcEngine/CalcEngine.cs, ClosedXML/Excel/CalcEngine/Functions/Financial.cs
I added a stub with financial formulas to CalcEngine.
I think this is solution can help anyone who want to add neccessary financial formulas.
=> Add stub for financial formulas

ClosedXML/Excel/CalcEngine/CalcEngine.cs, ClosedXML/Excel/CalcEngine/Functions/Engineering.cs
Stub for simple future implementation this formulas.
=> Add stub for engineering formulas

ClosedXML/ClosedXML.csproj, ClosedXML/Excel/Ranges/XLRangeBase.cs, ClosedXML_Tests/Excel/Ranges/MergedRangesTests.cs
Fixes #1517
Breaking change: Single cells won't merge
=> Avoid merging of a single cell. 

ClosedXML/Excel/Drawings/XLPictures.cs, ClosedXML_Tests/Excel/ImageHandling/PictureTests.cs
=> Fixed file is used in another process error

ClosedXML_Tests/Excel/ImageHandling/PictureTests.cs
=> Added concurrent check in thread safe way for excel workbook

ClosedXML/Excel/CalcEngine/Functions/MathTrig.cs, ClosedXML_Tests/Excel/CalcEngine/FunctionsTests.cs, ClosedXML_Tests/Excel/CalcEngine/MathTrigTests.cs
Fixes: https://github.com/ClosedXML/ClosedXML/issues/1534
=> #1534 Fix MROUND doesn't rounds correctly up

ClosedXML/Excel/XLWorkbook_Load.cs, ClosedXML_Tests/Excel/Loading/LoadingTests.cs
=> Load property "Modified" when loading workbook

ClosedXML/Excel/Cells/IXLCell.cs, ClosedXML/Excel/Cells/XLCell.cs, ClosedXML_Tests/Excel/Cells/XLCellTests.cs
=>  Implement sensible ToString override for XLCell

ClosedXML/Excel/CalcEngine/Functions/DateAndTime.cs, ClosedXML_Tests/Excel/CalcEngine/DateAndTimeTests.cs
Implement DATEDIF function for calculate difference between two dates.
MS specs: https://support.microsoft.com/en-us/office/datedif-function-25dba1a4-2812-480b-84dd-8b32a451b35c
=> Implement DATEDIF function

ClosedXML/Excel/CalcEngine/Functions/Statistical.cs, ClosedXML/Excel/CalcEngine/Functions/Tally.cs, ClosedXML_Tests/Excel/CalcEngine/StatisticalTests.cs
Supercedes #1514 
Closes #1514
=> Add GEOMEAN formula

ClosedXML/Excel/CalcEngine/Functions/Statistical.cs, ClosedXML_Tests/Excel/CalcEngine/StatisticalTests.cs
=> Add FISHER formula

ClosedXML/Excel/CalcEngine/Functions/Statistical.cs, ClosedXML/Excel/CalcEngine/Functions/Tally.cs, ClosedXML_Tests/Excel/CalcEngine/StatisticalTests.cs
=> DEVSQ formula

ClosedXML/Excel/IXLWorksheet.cs, ClosedXML/Excel/PivotTables/IXLPivotField.cs, ClosedXML/Excel/PivotTables/IXLPivotTable.cs, ClosedXML/Excel/PivotTables/XLPivotField.cs, ClosedXML/Excel/PivotTables/XLPivotTable.cs, ClosedXML/Excel/XLWorksheet.cs, ClosedXML_Tests/Excel/PivotTables/XLPivotTableTests.cs, ClosedXML_Tests/Excel/Worksheets/XLWorksheetTests.cs, ClosedXML_Tests/OpenXmlTests.cs, ClosedXML_Tests/Utils/PivotTableComparer.cs
Implement pivot table copying. Doesn't include pivot table formats yet.
=> Copy pivot tables on worksheet copy

ClosedXML.Tests/Excel/Columns/ColumnTests.cs, ClosedXML.Tests/Excel/Rows/RowTests.cs, ClosedXML/Excel/Ranges/XLRange.cs, ClosedXML/Excel/Ranges/XLRangeBase.cs, ClosedXML/Excel/XLCellsUsedOptions.cs
Checks `Worksheet.Internals.CellsCollection` for rows/columns used before  iterating.
=> Improve RowsUsed and ColumnsUsed performance

ClosedXML.Tests/Excel/CalcEngine/StatisticalTests.cs, ClosedXML/Excel/CalcEngine/Functions/Statistical.cs, ClosedXML/Excel/CalcEngine/Functions/Tally.cs
I've implemented the MEDIAN function. This is my first contribution. I'll be happy to receive feedback and suggestions on changes that I should make.
Resolves ClosedXML/ClosedXML#1715
=> Implements MEDIAN function

ClosedXML.Tests/Excel/CalcEngine/FormulaCachingTests.cs, ClosedXML/ClosedXML.csproj
=> Upgrade ExcelNumberFormat dependency to v1.1.0

ClosedXML.Tests/Excel/CalcEngine/FinancialTests.cs, ClosedXML/Excel/CalcEngine/Functions/Financial.cs
@igitur I am sorry, I screwed up with PR #1800, it was on a branch `develop` and it was causing me problems. Could you please look at it once again? I incorporated the suggested changes (last commit).
Fixes #1777
=> Implement PMT function
